### ISSUE TITLE
Why does jdbc not support custom sessionId

### ISSUE THREAD

**Issue by XiaoJiuDYS** [ClickHouse/clickhouse-jdbc#1017]
I want use TEMPORARY table in multiQuery,but i can't create it;
And i can't set session_id;

version 0.3.2 com.clickhouse
``` 
java.io.IOException: Code: 113. DB::Exception: There is no session or session context has expired. (THERE_IS_NO_SESSION) (version 21.9.4.35 (official build))

	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:130)
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:201)
	at com.clickhouse.client.http.ClickHouseHttpClient.postRequest(ClickHouseHttpClient.java:88)
	at com.clickhouse.client.http.ClickHouseHttpClient.execute(ClickHouseHttpClient.java:115)
	at com.clickhouse.client.ClickHouseRequest.execute(ClickHouseRequest.java:1375)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeStatement(ClickHouseStatementImpl.java:133)
	at com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.executeBatch(SqlBasedPreparedStatement.java:158)
	at com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.executeQuery(SqlBasedPreparedStatement.java:199)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:722)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:713)
```

**Comment by XiaoJiuDYS** [comment]
I read the source code and found that custom sessionId is not supported

**Comment by zhicwu** [comment]
Hi @XiaoJiuDYS, it's actually supported. When you issue multi-statement query, session will be created automatically. And if you prefer to set custom session id, you may pass property "session_id=mySessionId" when creating connection. In worst case, if none of them working, you may use `statement.unwrap(ClickHouseRequest.class).session("mySessionId")`, but it's not recommended.

**Comment by XiaoJiuDYS** [comment]
i just see the JdbcTemplate execute

> 

Thanks!! it worked
