### ISSUE TITLE
Can't retrieve Tuples in `SELECT *`, IllegalArgumentException: unknown data type. Projecting flattened names works OK though

### ISSUE THREAD

**Issue by acruise** [ClickHouse/clickhouse-jdbc#1025]
Hey folks,

When I `SELECT *` from a table that has Tuple fields, I get an IllegalArgumentException with the message `Unknown data type: srcdest String` (`srcdest` is the name of the nested field)

Here's the relevant section of the DDL (this is from the OpenSearch "logs" sample dataset):

```
  geo Tuple (
    srcdest char(5),
    src char(2),
    dest char(2),
    coordinates Tuple (
      lat double,
      lon double
    )
  ),
```

```
Caused by: java.lang.IllegalArgumentException: Unknown data type: srcdest String
	at com.clickhouse.client.ClickHouseDataType.of(ClickHouseDataType.java:187)
	at com.clickhouse.client.ClickHouseColumn.readColumn(ClickHouseColumn.java:289)
	at com.clickhouse.client.ClickHouseColumn.readColumn(ClickHouseColumn.java:231)
	at com.clickhouse.client.ClickHouseColumn.of(ClickHouseColumn.java:324)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor.readColumns(ClickHouseRowBinaryProcessor.java:581)
	at com.clickhouse.client.ClickHouseDataProcessor.<init>(ClickHouseDataProcessor.java:96)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor.<init>(ClickHouseRowBinaryProcessor.java:589)
	at com.clickhouse.client.ClickHouseDataStreamFactory.getProcessor(ClickHouseDataStreamFactory.java:47)
	at com.clickhouse.client.data.ClickHouseStreamResponse.<init>(ClickHouseStreamResponse.java:77)
	at com.clickhouse.client.data.ClickHouseStreamResponse.of(ClickHouseStreamResponse.java:54)
	at com.clickhouse.client.http.ClickHouseHttpClient.postRequest(ClickHouseHttpClient.java:90)
	at com.clickhouse.client.http.ClickHouseHttpClient.execute(ClickHouseHttpClient.java:115)
	at com.clickhouse.client.ClickHouseRequest.execute(ClickHouseRequest.java:1375)
	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:75)
	... 18 more
```

but when I flatten it myself with `SELECT geo.srcdest` it works fine. `SELECT *` from the HTTP interface works fine, returning the nested tuples (the `IN:US` in the paste below):

```
$ curl 'http://localhost:8123/?query=SELECT+*+FROM+opensearch_examples.logs+LIMIT+1'
Mozilla/5.0 (X11; Linux x86_64; rv:6.0a1) Gecko/20110421 Firefox/6.0a1	6219	223.87.60.27	deb	('IN:US','IN','US',(39.41042861,-88.8454325))	artifacts.opensearch.org	opensearch_dashboards_sample_data_logs	223.87.60.27	(8589934592,'win 8')	0	223.87.60.27 - - [2018-07-22T00:39:02.912Z] "GET /opensearch/opensearch-1.0.0.deb_1 HTTP/1.1" 200 6219 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:6.0a1) Gecko/20110421 Firefox/6.0a1"	0	http://twitter.com/success/wendy-lawrence	/opensearch/opensearch-1.0.0.deb	200	['success','info']	2018-07-22T00:39:02.912Z	https://artifacts.opensearch.org/downloads/opensearch/opensearch-1.0.0.deb_1	2018-07-22T00:39:02.912Z	('sample_web_logs')
```

Clickhouse version: 22.7.1.2484
JDBC driver version: 0.3.2

**Comment by zhicwu** [comment]
Hi @acruise, could you upgrade driver to 0.3.2-patch11? Named tuple was supported along with JSON data type since 0.3.2-patch8.

**Comment by acruise** [comment]
`-patch11` worked, thanks!
