### ISSUE TITLE
Can't use stream with Spring Boot 3 RC2.

### ISSUE THREAD

**Issue by dpswds** [ClickHouse/clickhouse-jdbc#1132]
Souce:
org.hibernate.query.Query<Record> query = session.createNativeQuery(sql, Record.class);
......
Stream<Record> stream = query.setReadOnly(true).setFetchSize(1000).setCacheable(false).stream();
.......
stream.forEach(rec -> {
.......
});

Exception:
Caused by: java.sql.SQLException: Cannot operate on a closed ResultSet
at com.clickhouse.jdbc.SqlExceptionUtils.clientError(SqlExceptionUtils.java:73)
at com.clickhouse.jdbc.AbstractResultSet.ensureOpen(AbstractResultSet.java:24)
at com.clickhouse.jdbc.ClickHouseResultSet.next(ClickHouseResultSet.java:708)
at com.zaxxer.hikari.pool.HikariProxyResultSet.next(HikariProxyResultSet.java)
at org.hibernate.sql.results.jdbc.internal.JdbcValuesResultSetImpl.lambda$processNext$0(JdbcValuesResultSetImpl.java:89)
... 89 common frames omitted

**Comment by zhicwu** [comment]
Thanks for the report @dpswds. Judging from the error, it looks like the ResultSet or the Statement it belongs to was closed somehow. Could you share a repo to reproduce the issue?

**Comment by dpswds** [comment]
this is not a clickhouse jdbc bug.
close.
