### ISSUE TITLE
[bug]  ClickHouseRowBinaryProcessor.MappedFunctions#writeArray asArray strong turn indicates an error

### ISSUE THREAD

**Issue by duhanmin** [ClickHouse/clickhouse-jdbc#1135]
```
java.lang.ClassCastException: class [Ljava.lang.Integer; cannot be cast to class [I ([Ljava.lang.Integer; and [I are in module java.base of loader 'bootstrap')
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$MappedFunctions.writeArray(ClickHouseRowBinaryProcessor.java:76)
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$MappedFunctions.serialize(ClickHouseRowBinaryProcessor.java:491)
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.addBatch(InputBasedPreparedStatement.java:333)

```

**Comment by zhicwu** [comment]
Hi @duhanmin, serialization was refactored in PR #1124 with breaking changes. Could you try nightly build at [here](https://s01.oss.sonatype.org/content/repositories/snapshots/com/clickhouse/clickhouse-jdbc/0.3.3-SNAPSHOT/) and see if it will work for you case?

**Comment by chernser** [comment]
Not enough information. 
Closing
