### ISSUE TITLE
Found interface com.clickhouse.jdbc.ClickHouseConnection but class was expected

### ISSUE THREAD

**Issue by javadiggy** [ClickHouse/clickhouse-jdbc#1147]
Dependency clickhouse-jdbc 0.3.2-patch-11
Java 11
Spring boot 2.7.4

How to fix this problem?

**Comment by zhicwu** [comment]
Hi @javadiggy, could you elaborate? What's the exact error(stack trace)? Are you having problem using JDBC driver to connect to database?

**Comment by javadiggy** [comment]
Hi @zhicwu , we are using jdbc clickhouse driver

2022-12-06 17:23:55,349 INFO [main] r.s.r.s.c.ApplicationKt - Starting ConnectorApplicationKt using Java 11.0.17 on feed-connector-6-gqkl5 with PID 1 (/home/jboss/package.jar started by 1002570000 in /home/jboss) 
 2022-12-06 17:23:55,397 INFO [main] r.s.r.s.c.ConnectorApplicationKt - The following 1 profile is active: "deploy" 
 2022-12-06 17:24:05,072 INFO [main] o.s.b.w.e.t.TomcatWebServer - Tomcat initialized with port(s): 8241 (http) 
 2022-12-06 17:24:05,180 INFO [main] o.a.c.h.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-8241"] 
 2022-12-06 17:24:05,181 INFO [main] o.a.c.c.StandardService - Starting service [Tomcat] 
 2022-12-06 17:24:05,182 INFO [main] o.a.c.c.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.65] 
 2022-12-06 17:24:05,700 INFO [main] o.a.c.c.C.[.[.[/com/example/project] - Initializing Spring embedded WebApplicationContext 
 2022-12-06 17:24:05,701 INFO [main] o.s.b.w.s.c.ServletWebServerApplicationContext - Root WebApplicationContext: initialization completed in 10050 ms 
 2022-12-06 17:24:09,405 INFO [main] c.z.h.HikariDataSource - HikariPool-1 - Starting... 
 2022-12-06 17:24:10,275 INFO [main] c.z.h.HikariDataSource - HikariPool-1 - Start completed. 
 2022-12-06 17:24:10,410 WARN [main] o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'databaseConfig': Invocation of init method failed; nested exception is java.lang.IncompatibleClassChangeError: Found interface com.clickhouse.jdbc.ClickHouseConnection, but class was expected 
 2022-12-06 17:24:10,477 INFO [main] c.z.h.HikariDataSource - HikariPool-1 - Shutdown initiated... 
 2022-12-06 17:24:10,497 INFO [main] c.z.h.HikariDataSource - HikariPool-1 - Shutdown completed. 
 2022-12-06 17:24:10,505 INFO [main] o.a.c.c.StandardService - Stopping service [Tomcat] 
 2022-12-06 17:24:10,584 INFO [main] o.s.b.a.l.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
 2022-12-06 17:24:10,709 ERROR [main] o.s.b.SpringApplication - Application run failed 
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'databaseConfig': Invocation of init method failed; nested exception is java.lang.IncompatibleClassChangeError: Found interface com.clickhouse.jdbc.ClickHouseConnection, but class was expected
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at ru.sbrf.rmc.storage.connector.ConnectorApplicationKt.main(ConnectorApplication.kt:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.clickhouse.jdbc.ClickHouseConnection, but class was expected
	at com.clickhouse.jdbc.ClickHouseConnection.createStatement(ClickHouseConnection.java)
	at com.clickhouse.jdbc.ClickHouseConnection.createStatement(ClickHouseConnection.java:25)
	at com.zaxxer.hikari.pool.ProxyConnection.createStatement(ProxyConnection.java:294)
	at com.zaxxer.hikari.pool.HikariProxyConnection.createStatement(HikariProxyConnection.java)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:379)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:431)
	at ru.sbrf.rmc.storage.connector.config.database.DatabaseConfig.checkDataSourceConnection(DatabaseConfig.kt:16)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 26 common frames omitted

**Comment by zhicwu** [comment]
@javadiggy, can you check your classpath and pom to ensure exact same version of ClickHouse JDBC is used? Apart from that, please use shaded jar like below to avoid potential conflict of dependencies.

```xml
<dependency>
    <groupId>com.clickhouse</groupId>
    <artifactId>clickhouse-jdbc</artifactId>
    <version>0.3.2-patch11</version>
    <classifier>http</classifier>
    <exclusions>
        <exclusion>
            <groupId>*</groupId>
            <artifactId>*</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by Delphin1** [comment]
We got the same error in our scala/zio code. Moreover, the error is reproduced only in
one of our EKS clusters. It is very strange.
We use sbt:
```
val deps = Seq(
"com.clickhouse" % "clickhouse-jdbc" % "0.3.2-patch11",
...
)
```

**Comment by Delphin1** [comment]
In our case, it turned out that the reason was the [dynatrace java agent](https://www.dynatrace.com/support/help/how-to-use-dynatrace/infrastructure-monitoring/cloud-platform-monitoring/amazon-web-services-monitoring/aws-supporting-service-metrics/eks) that is used on our EKS clusters.

**Comment by zhicwu** [comment]
> In our case, it turned out that the reason was the [dynatrace java agent](https://www.dynatrace.com/support/help/how-to-use-dynatrace/infrastructure-monitoring/cloud-platform-monitoring/amazon-web-services-monitoring/aws-supporting-service-metrics/eks) that is used on our EKS clusters.

Thanks for sharing your findings. It is recommended to use shaded jar to avoid lib conflict/missing. See comment at [here](https://github.com/ClickHouse/clickhouse-jdbc/issues/1185#issuecomment-1375689199).
