### ISSUE TITLE
java.io.EOFException: reached end of stream after reading 235827 bytes; 320565 bytes expected

### ISSUE THREAD

**Issue by jackmed** [ClickHouse/clickhouse-jdbc#1149]
Hi, When doing an execute on an query prepared statement with JdbcTemplate, I got this error:
```
Caused by: java.io.EOFException: reached end of stream after reading 235827 bytes; 320565 bytes expected
	at ru.yandex.clickhouse.util.Utils.readFully(Utils.java:171)
	at ru.yandex.clickhouse.util.Utils.readFully(Utils.java:147)
	at ru.yandex.clickhouse.response.ClickHouseLZ4Stream.readNextBlock(ClickHouseLZ4Stream.java:102)
	at ru.yandex.clickhouse.response.ClickHouseLZ4Stream.checkNext(ClickHouseLZ4Stream.java:75)
	at ru.yandex.clickhouse.response.ClickHouseLZ4Stream.read(ClickHouseLZ4Stream.java:61)
	at ru.yandex.clickhouse.response.StreamSplitter.readFromStream(StreamSplitter.java:92)
	at ru.yandex.clickhouse.response.StreamSplitter.next(StreamSplitter.java:63)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.hasNext(ClickHouseResultSet.java:153)
	... 34 common frames omitted
```

ru.yandex.clickhouse/clickhouse-jdbc version: 0.3.0
clickhouse version: 22.3.8.39

I would be grateful for any ideas.

**Comment by zhicwu** [comment]
Hi @jackmed, it looks like something wrong with decompression, deserialization or the network. Have you tried to upgrade the driver the latest?

**Comment by jackmed** [comment]
I do not upgrade the driver, but When I execute  query again, it works!

Maybe, you are right
`it looks like something wrong with decompression, deserialization or the network. `

Thank  you very much.
