### ISSUE TITLE
com.clickhouse.client.ClickHouseDateTimeValue#219 asString(int length, Charset charset) transformation caused Exception

### ISSUE THREAD

**Issue by majian7805** [ClickHouse/clickhouse-jdbc#1156]
Hello,

This is my first question here, so apologies in advance if I missed any information and pls let me know if more info is needed.

We have a table with a column defined as such

>  `create_time`   DateTime COMMENT '创建时间',

However, when we attempt to query the data in a specified time range, defined as such

> select * from temp WHERE create_time >==]]> #{beginDate,jdbcType=TIMESTAMP} AND create_time #{endDate,jdbcType=TIMESTAMP};

we are getting errors and on debugging it seems like time(Long) would be transfered to time(String).

`org.jkiss.dbeaver.model.sql.DBSQLException: SQL 错误 [53]: ClickHouse exception, code: 53, host: xxx, port: 8123; Code: 53, e.displayText() = DB::Exception: Cannot convert string 2022-12-19 23:59:59.999 to type DateTime: while executing 'FUNCTION lessOrEquals(create_time : 2, '2022-12-19 23:59:59.999' : 4) -> lessOrEquals(create_time, '2022-12-19 23:59:59.999') UInt8 : 10' (version 21.1.2.15 (official build))

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:509)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$0(SQLQueryJob.java:440)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:427)

	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:812)

	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3245)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)

	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:169)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)

	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4576)

	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)

	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

Caused by: ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 53, host: 10.20.155.131, port: 8123; Code: 53, e.displayText() = DB::Exception: Cannot convert string 2022-11-16 23:59:59.999 to type DateTime: while executing 'FUNCTION lessOrEquals(create_time : 2, '2022-11-16 23:59:59.999' : 4) -> lessOrEquals(create_time, '2022-11-16 23:59:59.999') UInt8 : 10' (version 21.1.2.15 (official build))

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:58)

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:1046)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:737)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:196)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:166)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:161)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:156)

	at ru.yandex.clickhouse.ClickHouseStatementImpl.execute(ClickHouseStatementImpl.java:328)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:327)

	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:130)

	... 12 more

Caused by: java.lang.Throwable: Code: 53, e.displayText() = DB::Exception: Cannot convert string 2022-11-16 23:59:59.999 to type DateTime: while executing 'FUNCTION lessOrEquals(create_time : 2, '2022-11-16 23:59:59.999' : 4) -> lessOrEquals(create_time, '2022-11-16 23:59:59.999') UInt8 : 10' (version 21.1.2.15 (official build))

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:53)
`

And this depends on the driverclass name set in application.properties.

my pom.xml is 

`<dependency>
    <groupId>ru.yandex.clickhouse</groupId>
    <artifactId>clickhouse-jdbc</artifactId>
    <version>0.3.2</version>
</dependency>
`

when I set the driverclass name as such in application.properties:

> spring.datasource.driver-class-name=cru.yandex.clickhouse.ClickHouseDriver

there is no error.

But when I set the driverclass name using the new one as such in application.properties:

> spring.datasource.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver

it comes out. 

I've located the problem by debugging and found problem may be in "com.clickhouse.client.ClickHouseValues#86 DATETIME_FORMATTER" and "com.clickhouse.client.ClickHouseDateTimeValue#219 asString(int length, Charset charset)"

Can you please help? Thanks!

**Comment by zhicwu** [comment]
Hi @majian7805, the problem is the driver is not smart enough to figure out exact data type of these parameters, because ClickHouse does not support prepared statement.

Anyway, based on the information you provided, please consider to:
1. change maven group id to `com.clickhouse` and bump the driver to latest version (e.g. 0.3.2-patch11) first
2. if you're using `DateTime` or `DateTime32` and not going to switch to `DateTime64`, you may set timestamp parameters like below:
  ```java
  PreparedStatement ps = conn.preparedStatement("select * from table where create_time between ? and ?");
  // prefer to use LocalDateTime for timestamp without timezone
  // remove truncatedTo(ChronoUnit.SECONDS) if the target column is DateTime64, or if you change the query to:
  // "select * from table where create_time between parseDateTimeBestEffort(?) and parseDateTimeBestEffort(?)"
  ps.setObejct(1, LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS));
  ps.setObejct(2, LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS));
  ps.executeQuery();
  ```

**Comment by majian7805** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by majian7805** [comment]
> Hi @majian7805, the problem is the driver is not smart enough to figure out exact data type of these parameters, because ClickHouse does not support prepared statement.
> 
> Anyway, based on the information you provided, please consider to:
> 
> 1. change maven group id to `com.clickhouse` and bump the driver to latest version (e.g. 0.3.2-patch11) first
> 2. if you're using `DateTime` or `DateTime32` and not going to switch to `DateTime64`, you may set timestamp parameters like below:
> 
> ```java
> PreparedStatement ps = conn.preparedStatement("select * from table where create_time between ? and ?");
> // prefer to use LocalDateTime for timestamp without timezone
> // remove truncatedTo(ChronoUnit.SECONDS) if the target column is DateTime64, or if you change the query to:
> // "select * from table where create_time between parseDateTimeBestEffort(?) and parseDateTimeBestEffort(?)"
> ps.setObejct(1, LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS));
> ps.setObejct(2, LocalDateTime.now().truncatedTo(ChronoUnit.SECONDS));
> ps.executeQuery();
> ```

thank U, I've already dealed with the precision of time and fixed.

**Comment by lichong-a** [comment]
When can the type be automatically inferred?

**Comment by majian7805** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
