### ISSUE TITLE
Driver class com.clickhouse.jdbc.ClickHouseDriver is not found

### ISSUE THREAD

**Issue by fzhan** [ClickHouse/clickhouse-jdbc#1176]
Hello,

I have followed the instruction listed on https://clickhouse.com/docs/en/integrations/nifi-and-clickhouse/, made sure:
1. Downloaded the latest released shaded jar "clickhouse-cli-client-0.3.2-patch11-shaded.jar"
2. Placed it under the lib dir
3. Made sure it's permission is the same as other jar in the same dir (nifi:nifi)
```
drwxrwx--- 2 nifi nifi     4096 Oct  3 17:49 aspectj
drwxrwx--- 2 nifi nifi     4096 Oct  3 17:49 bootstrap
-rw-rw-r-- 1 nifi nifi   713089 Jan  5 04:13 clickhouse-cli-client-0.3.2-patch11-shaded.jar
drwxrwsr-x 2 root nifi        1 Jan  4 11:47 custom
drwxrwx--- 2 nifi nifi     4096 Oct  3 17:49 java11
-rw-rw-r-- 1 nifi nifi    95806 Oct  3 17:49 javax.servlet-api-3.1.0.jar
-rw-rw-r-- 1 nifi nifi    16555 Oct  3 17:49 jcl-over-slf4j-1.7.36.jar
-rw-rw-r-- 1 nifi nifi   564365 Oct  3 17:49 jetty-schemas-5.2.jar
-rw-rw-r-- 1 nifi nifi     4519 Oct  3 17:49 jul-to-slf4j-1.7.36.jar
-rw-rw-r-- 1 nifi nifi    23715 Oct  3 17:49 log4j-over-slf4j-1.7.36.jar
-rw-rw-r-- 1 nifi nifi   231851 Oct  3 17:49 logback-classic-1.2.11.jar
```
4. Still failed to find the class
```
2023-01-05T12:18:48.899558385+08:00 2023-01-05 04:18:48,549 ERROR [Timer-Driven Process Thread-3] o.a.n.c.s.StandardControllerServiceNode StandardControllerServiceNode[service=DBCPConnectionPool[id=7c890849-0185-1000-ffff-ffffd101b6e9], name=ClickHouse JDBC, active=true] Failed to invoke @OnEnabled method

2023-01-05T12:18:48.899579695+08:00 org.apache.nifi.processor.exception.ProcessException: Driver class com.clickhouse.jdbc.ClickHouseDriver is not found

2023-01-05T12:18:48.899590327+08:00 	at org.apache.nifi.dbcp.DBCPConnectionPool.getDriver(DBCPConnectionPool.java:588)

2023-01-05T12:18:48.899599101+08:00 	at org.apache.nifi.dbcp.DBCPConnectionPool.configureDataSource(DBCPConnectionPool.java:525)

2023-01-05T12:18:48.899607739+08:00 	at org.apache.nifi.dbcp.DBCPConnectionPool.onConfigured(DBCPConnectionPool.java:497)

2023-01-05T12:18:48.899616708+08:00 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2023-01-05T12:18:48.899671550+08:00 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

2023-01-05T12:18:48.899683222+08:00 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

2023-01-05T12:18:48.899692195+08:00 	at java.lang.reflect.Method.invoke(Method.java:498)

2023-01-05T12:18:48.899718268+08:00 	at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:145)

2023-01-05T12:18:48.899729310+08:00 	at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:133)

2023-01-05T12:18:48.899738237+08:00 	at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotations(ReflectionUtils.java:78)

2023-01-05T12:18:48.899746823+08:00 	at org.apache.nifi.util.ReflectionUtils.invokeMethodsWithAnnotation(ReflectionUtils.java:55)

2023-01-05T12:18:48.899755665+08:00 	at org.apache.nifi.controller.service.StandardControllerServiceNode$2.run(StandardControllerServiceNode.java:598)

2023-01-05T12:18:48.899763988+08:00 	at org.apache.nifi.engine.FlowEngine$2.run(FlowEngine.java:110)

2023-01-05T12:18:48.899773267+08:00 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

2023-01-05T12:18:48.899781368+08:00 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

2023-01-05T12:18:48.899809557+08:00 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

2023-01-05T12:18:48.899818980+08:00 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

2023-01-05T12:18:48.899827588+08:00 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

2023-01-05T12:18:48.899836276+08:00 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

2023-01-05T12:18:48.899844973+08:00 	at java.lang.Thread.run(Thread.java:750)

2023-01-05T12:18:48.899853329+08:00 Caused by: java.lang.ClassNotFoundException: com.clickhouse.jdbc.ClickHouseDriver

2023-01-05T12:18:48.899862179+08:00 	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)

2023-01-05T12:18:48.899889711+08:00 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)

2023-01-05T12:18:48.899898561+08:00 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

2023-01-05T12:18:48.899906829+08:00 	at java.lang.Class.forName0(Native Method)

2023-01-05T12:18:48.899914859+08:00 	at java.lang.Class.forName(Class.java:264)

2023-01-05T12:18:48.899922812+08:00 	at org.apache.nifi.dbcp.DBCPConnectionPool.getDriver(DBCPConnectionPool.java:586)

2023-01-05T12:18:48.899931525+08:00 	... 19 common frames omitted
```

**Comment by fzhan** [comment]
Just realized the file needed is actually clickhouse-jdbc rather than clickhouse-cli-client. My bad!
