### ISSUE TITLE
trying to connect to clickhouse with r2dbc url (0.4.0)

### ISSUE THREAD

**Issue by BliZzZzZarD** [ClickHouse/clickhouse-jdbc#1208]
I'm trying to connect to clickhouse with r2dbc url (0.4.0):

@Configuration
@RequiredArgsConstructor
public class R2DBCConfig {
    private final ClickHouseProperties properties;
    @Bean
    public ConnectionFactory clickHouseConnectionFactory() {
        return get(format(
                "r2dbc:clickhouse:http://%s:%s@%s:%d/%s",
                properties.getUser(),
                properties.getPassword(),
                properties.getHost(),
                properties.getPort(),
                properties.getDatabase()
        ));
    }
}

but i get an error: 

Caused by: java.util.ServiceConfigurationError: io.r2dbc.spi.ConnectionFactoryProvider: Provider com.clickhouse.r2dbc.connection.ClickHouseConnectionFactoryProvider could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586) ~[na:na]
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813) ~[na:na]
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729) ~[na:na]
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403) ~[na:na]
	at io.r2dbc.spi.ConnectionFactories.find(ConnectionFactories.java:108) ~[r2dbc-spi-1.0.0.RELEASE.jar:na]
	at io.r2dbc.spi.ConnectionFactories.get(ConnectionFactories.java:140) ~[r2dbc-spi-1.0.0.RELEASE.jar:na]
	at io.r2dbc.spi.ConnectionFactories.get(ConnectionFactories.java:128) ~[r2dbc-spi-1.0.0.RELEASE.jar:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.2.jar:6.0.2]
	... 62 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/clickhouse/client/ClickHouseClient
	at com.clickhouse.r2dbc.connection.ClickHouseConnectionFactoryProvider.<clinit>(ClickHouseConnectionFactoryProvider.java:37) ~[clickhouse-r2dbc-0.4.0.jar:clickhouse-r2dbc 0.4.0 (revision: 3a53cf1)]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789) ~[na:na]
	... 78 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.clickhouse.client.ClickHouseClient
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 85 common frames omitted

I traced the crash  point in package r2dbc: Iterator var1 = loadProviders().iterator(); 
it seems funny because if i set a breakpoint and call a method in the debugger then the instance is created without errors. But if you run app without breakpoints, you will get an error.

What's wrong?

**Comment by ivan-klass** [comment]
I think I may have a related issue - class loader now (after update to 0.4.0) fails to load class by name:
`com.clickhouse.jdbc.ClickHouseDriver`
stacktrace:
```
java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520),
java.base/java.lang.Class.forName0(Native Method)
java.base/java.lang.Class.forName(Class.java:375)
doobie.util.transactor$Transactor$fromDriverManager$.$anonfun$1(transactor.scala:355)
...
```

I'm instantiating it using `doobie`

```scala
Transactor.fromDriverManager[F](
  "com.clickhouse.jdbc.ClickHouseDriver",
  s"jdbc:ch:http${if (security) "s" else ""}://$host:$port/$db?security=$security",
  user,
  password
)
```

**Comment by zhicwu** [comment]
Hi @BliZzZzZarD, could you try shaded jar?

```xml
<dependency>
    <groupId>com.clickhouse</groupId>
    <artifactId>clickhouse-r2dbc</artifactId>
    <version>0.4.0</version>
    <!-- use uber jar with all dependencies included, change classifier to http for smaller jar -->
    <classifier>all</classifier>
    <exclusions>
        <exclusion>
            <groupId>*</groupId>
            <artifactId>*</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by BliZzZzZarD** [comment]
> ```
> 
> ```

thanks, it works. connection is created but now i have a new truble:

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.r2dbc.core.DatabaseClient]: Factory method 'r2dbcDatabaseClient' threw exception with message: Cannot determine a BindMarkersFactory for ClickHouse using com.clickhouse.r2dbc.connection.ClickHouseConnectionFactory@9263c54
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.2.jar:6.0.2]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648) ~[spring-beans-6.0.2.jar:6.0.2]
	... 19 common frames omitted
Caused by: org.springframework.r2dbc.core.binding.BindMarkersFactoryResolver$NoBindMarkersFactoryException: Cannot determine a BindMarkersFactory for ClickHouse using com.clickhouse.r2dbc.connection.ClickHouseConnectionFactory@9263c54
	at org.springframework.r2dbc.core.binding.BindMarkersFactoryResolver.resolve(BindMarkersFactoryResolver.java:61) ~[spring-r2dbc-6.0.2.jar:6.0.2]
	at org.springframework.r2dbc.core.DefaultDatabaseClientBuilder.build(DefaultDatabaseClientBuilder.java:86) ~[spring-r2dbc-6.0.2.jar:6.0.2]
	at org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryDependentConfiguration.r2dbcDatabaseClient(ConnectionFactoryDependentConfiguration.java:41) ~[spring-boot-autoconfigure-3.0.0.jar:3.0.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.2.jar:6.0.2]
	... 20 common frames omitted

for information: java 17, spring boot 3.0.0

**Comment by zhicwu** [comment]
A quick searched showed ClickHouse is not supported by default. Perhaps you can use BindMarkersFactory directly or try MySQL instead? This is beyond what the r2dbc driver is capable of.

https://github.com/spring-projects/spring-framework/blob/e3fb0a39a29f1d4b49a9e8dc31e287c6af94e540/spring-r2dbc/src/main/java/org/springframework/r2dbc/core/binding/BindMarkersFactoryResolver.java#L120-L127

**Comment by BliZzZzZarD** [comment]
zhicwu Thanks for your participation. The question is not actual from my very first comment. I didn't take this setting into account at the beginning:

@SpringBootApplication(exclude = {R2dbcAutoConfiguration.class, R2dbcDataAutoConfiguration.class})

Everything works.
