### ISSUE TITLE
IOException

### ISSUE THREAD

**Issue by huihuilee** [ClickHouse/clickhouse-jdbc#207]
using 0.1.39 version

Caused by: java.sql.SQLException: java.io.IOException: Attempted read on closed stream.
	at ru.yandex.clickhouse.response.ClickHouseResultSet.hasNext(ClickHouseResultSet.java:131)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.next(ClickHouseResultSet.java:145)
	at com.dtstack.spl.clickhouse.engine.CkEngine.query(CkEngine.java:43)

**Comment by sourirer** [comment]
Check you code to confirm you don't close your connection to clickhouse before you finish read data .

**Comment by zhicwu** [comment]
Close stale issue/question.
