### ISSUE TITLE
Is there a rich sql management studio that works with clickhouse-jdbc?

### ISSUE THREAD

**Issue by umaxfun** [ClickHouse/clickhouse-jdbc#21]
Hi all,

Is there a rich sql management studio that works with Clickhouse via clickhouse-jdbc correctly? I've tried DBVisualizer, and SQLWorkbench, they cannot create and alter tables, and even cannot show table data, wrong syntax 🚆 

<img width="744" alt="screen shot 2016-09-11 at 17 34 26" src="https://cloud.githubusercontent.com/assets/521752/18417961/0ffede3a-7846-11e6-8343-4fdb17e00e30.png">

**Comment by serebrserg** [comment]
Hello,
I've tried it with SQuirreL, and it worked at least it showed table data.
No specific testing with SQL IDEs was done.
This depends on what queries the IDE is generating for the operations and in fact it depends on clickhouse-jdbc not much, because it modifies queries only by adding format for some types of queries by prefix and then just passes queries to ClickHouse.
Could you provide some examples of operations and queries that are generated?

**Comment by umaxfun** [comment]
This is the query for Jetbrains Datagrip and DBVisualizer: `SELECT t.* FROM "default".newTable t FORMAT TabSeparatedWithNamesAndTypes;`

<img width="788" alt="screen shot 2016-09-25 at 14 00 07" src="https://cloud.githubusercontent.com/assets/521752/18814892/be986442-8328-11e6-8fe0-aecdf4659ffc.png">

**Comment by umaxfun** [comment]
I see, all the studios I've tried generate table names in queries prefixed with "default". 
E.g. this one
<img width="297" alt="screen shot 2016-09-27 at 01 47 23" src="https://cloud.githubusercontent.com/assets/521752/18854476/6979a03e-8454-11e6-8699-fd2d593a6cc3.png">
results in `ClickHouse exception, code: 62, host: localhost, port: 8123; Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 12: "default".tvals, expected identifier, e.what() = DB::Exception`

**Comment by serebrserg** [comment]
Thanks.
The problem here is in quote characters the database name is surrounded by. JDBC driver does nothing with that, and ClickHouse doesn't expect that.
The question is why do all the studios surround database name by quotes. I'll check it.

**Comment by alexey-milovidov** [comment]
I don't know about JDBC, but ODBC interface provides information about quote character.
I think, JDBC has something similar and you could implement it.

**Comment by stepanselyuk** [comment]
@umaxfun how did you connected clickhouse-jdbc with DataGrip? I compiled the driver (both options w/ and w/o [assembly:single] ). With Url: `jdbc:clickhouse://localhost:8123`, but I got exception:
```
Error: Connection to ClickHouse - test failed: Exception in thread "main" java.lang.InstantiationException: java.sql.Driver at java.lang.Class.newInstance(Class.java:427) at com.intellij.database.remote.RemoteJdbcServer.main(RemoteJdbcServer.java:15) Caused by: java.lang.NoSuchMethodException: java.sql.Driver. () at java.lang.Class.getConstructor0(Class.java:3082) at java.lang.Class.newInstance(Class.java:412) ... 1 more .
```
Not sure, but maybe because I use port forwarding (clickhouse is living inside docker inside vagrant box), or because I trying to use SSH tunnel (to avoid port forwarding). Can you please provide more screens about how your settings in DataGrip?

**Comment by stepanselyuk** [comment]
Seems I understood:
<img width="1119" alt="screen_shot_2016-10-20_at_17 48 42" src="https://cloud.githubusercontent.com/assets/2071269/19565051/4433d32e-96ee-11e6-8f8c-48148e58ddd0.png">
<img width="1120" alt="screen_shot_2016-10-20_at_17 49 31" src="https://cloud.githubusercontent.com/assets/2071269/19565055/471ce6b6-96ee-11e6-8737-b2e08b9378df.png">
<img width="361" alt="screen_shot_on_2016-10-20_at_17_52_16" src="https://cloud.githubusercontent.com/assets/2071269/19565057/4a88c66c-96ee-11e6-8776-122c6fa349c2.png">

**Comment by amaslak** [comment]
Query ```select * from table limit 100``` works fine for me in IDEA 2.3 Preview with jdbc url ```jdbc:clickhouse://localhost:9001/my_schema``` while using ssh tunnel over ipv6.

The only problem is that idea can never close connection to clickhouse until i manually click disconnect button, then i get this exception in Output tab:
```
[2016-10-26 02:55:13] Cancelling...
[2016-10-26 02:55:15] java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
[2016-10-26 02:55:15] java.lang.RuntimeException: java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
	at com.intellij.execution.rmi.RemoteUtil.invokeRemote(RemoteUtil.java:179)
	at com.intellij.execution.rmi.RemoteUtil.access$300(RemoteUtil.java:36)
	at com.intellij.execution.rmi.RemoteUtil$RemoteInvocationHandler.invoke(RemoteUtil.java:274)
	at com.sun.proxy.$Proxy165.getWarnings(Unknown Source)
	at com.intellij.database.console.JdbcEngine.printWarnings(JdbcEngine.java:467)
	at com.intellij.database.console.JdbcEngine.executeQueryInner(JdbcEngine.java:420)
	at com.intellij.database.console.JdbcEngine.lambda$visitQuery$2(JdbcEngine.java:223)
	at com.intellij.database.console.AbstractEngine.lambda$submitRequest$3(AbstractEngine.java:171)
	at com.intellij.database.console.AbstractEngine.lambda$submitRunnable$2(AbstractEngine.java:148)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.rmi.ConnectException: Connection refused to host: localhost; nested exception is: 
	java.net.ConnectException: Connection refused (Connection refused)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:130)
	at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227)
	at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179)
	at com.sun.proxy.$Proxy164.getWarnings(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.execution.rmi.RemoteUtil.invokeRemote(RemoteUtil.java:169)
	... 13 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.$$YJP$$socketConnect(Native Method)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
```

**Comment by fabura** [comment]
@amaslak But it won't work if you add alias for your table like: select t.* from my_table as t limit 100;
Idea by default create queries with aliases to show table's content.

**Comment by umaxfun** [comment]
@amaslak I've already contacted Jetbrains support on this behaviour. They've saud that it's an issue with JDBC driver itself. Since I don't know any Java, I didn't get the point of the response :)))

<img width="622" alt="screen shot 2016-10-26 at 15 08 55" src="https://cloud.githubusercontent.com/assets/521752/19725442/2b52244c-9b8e-11e6-83f2-3e8a11d50d7d.png">

**Comment by amaslak** [comment]
@fabura
You're right, simple unit test reproduces the problem. Seems issue is with ClickHouse itself as it doesnt suppot ```t.*``` syntax.

**Comment by alexey-milovidov** [comment]
Probably we could add quick workaround to have basic support of syntax with table aliases.

**Comment by umaxfun** [comment]
Improvement in DataGrip was not detected in fact =)
<img width="961" alt="screen shot 2016-11-25 at 02 37 46" src="https://cloud.githubusercontent.com/assets/521752/20611283/711d53fc-b2b8-11e6-8b60-6f06885c3db3.png">

**Comment by umaxfun** [comment]
<img width="962" alt="screen shot 2016-11-25 at 02 41 20" src="https://cloud.githubusercontent.com/assets/521752/20611298/b119544c-b2b8-11e6-83f7-ed1857e9f1c5.png">

**Comment by umaxfun** [comment]
<img width="595" alt="screen shot 2016-11-25 at 02 41 53" src="https://cloud.githubusercontent.com/assets/521752/20611308/c3e485ba-b2b8-11e6-8e12-36e3292eb744.png">

**Comment by umaxfun** [comment]
<img width="1247" alt="screen shot 2016-11-25 at 02 52 53" src="https://cloud.githubusercontent.com/assets/521752/20611390/5a2825b2-b2ba-11e6-83af-e1876f0c351a.png">
Cannot find an error =(

**Comment by serebrserg** [comment]
The improvement was that it doesn't hang up after a query. It seems it is partial - it doesn't hang up at least for select queries now, but does so for creates and inserts. This still needs research.
It seems I have found a place to disable quotes around databases, but haven't found how to disable table aliases.
If you want selects the easiest way is to write them out as text.

**Comment by ijin82** [comment]
That works with DBeaver 
Database -> Driver Manager -> New
Then add file *clickhouse-jdbc-0.1-SNAPSHOT-jar-with-dependencies.jar* (or new version)
![dbeaver](https://cloud.githubusercontent.com/assets/612918/20625884/0a145420-b327-11e6-988f-e02541ead2dd.png)

**Comment by SaltTan** [comment]
I use SQL Workbench/J.
For better support I added some options into _.sqlworkbench/workbench.settings_.

For the 'Data' page to work:
`workbench.db.clickhouse.catalogs.supported=false`

For the 'SQL source' page to show the full 'create table' statement.
`workbench.db.clickhouse.retrieve.create.table.enabled=true`
`workbench.db.clickhouse.retrieve.create.table.query=show create table %fq_table_name%`

**Comment by tobia** [comment]
I think one of the main problems is that this driver exposes the database names as schemas, while the management tools work much better with catalogs. See issue #94

**Comment by meshpaul** [comment]
It works in DB visualizer.  The JDBC has to be packeged with dependecies

**Comment by zhicwu** [comment]
Close as this JDBC driver works in most popular SQL client well. However, clients like SQLWorkBench and SQuirreL should be enhanced to support complex data type like array and tuple, which work well in DBeaver and DataGrip.
