### ISSUE TITLE
Spark Scala + guava error

### ISSUE THREAD

**Issue by Yensan** [ClickHouse/clickhouse-jdbc#248]
Spark 2.3.1,   Scala 2.11.8,     Java 1.8.0_181
ClickHouse JDBC 0.1.40 (it use guava 19.0)
```scala
import ru.yandex.clickhouse.ClickHouseDriver
import ru.yandex.clickhouse.settings.ClickHouseProperties
import java.sql.{Connection, SQLException}
import java.util.Properties
import org.apache.spark.sql.SparkSession

val sparkSession = SparkSession.builder.config(conf)

val jdbcHostname = "localhost"
val jdbcProtocol = "clickhouse"
val jdbcPort = 8123
val jdbcDatabase = "hrdap"
val jdbcUsername = "default"
val jdbcPasswd = ""
val jdbcDriver = "ru.yandex.clickhouse.ClickHouseDriver"

val ckProperties = new Properties
ckProperties.put("user", jdbcUsername)
ckProperties.put("password", jdbcPasswd)

val jdbcUrl = s"jdbc:${jdbcProtocol}://${jdbcHostname}:${jdbcPort}/${jdbcDatabase}"
import org.apache.spark.sql.SaveMode

testdf.write.mode(SaveMode.Append).jdbc(url=jdbcUrl,
                  table="t", connectionProperties=ckProperties)
```

cause error
```
Name: org.apache.spark.SparkException
Message: Job aborted due to stage failure: Task 2 in stage 3.0 failed 1 times, most recent failure: Lost task 2.0 in stage 3.0 (TID 14, localhost, executor driver): java.lang.NoClassDefFoundError: Could not initialize class ru.yandex.clickhouse.ClickHouseUtil
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.setString(ClickHousePreparedStatementImpl.java:212)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$org$apache$spark$sql$execution$datasources$jdbc$JdbcUtils$$makeSetter$8.apply(JdbcUtils.scala:543)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$org$apache$spark$sql$execution$datasources$jdbc$JdbcUtils$$makeSetter$8.apply(JdbcUtils.scala:542)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$.savePartition(JdbcUtils.scala:647)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$saveTable$1.apply(JdbcUtils.scala:821)
	at org.apache.spark.sql.execution.datasources.jdbc.JdbcUtils$$anonfun$saveTable$1.apply(JdbcUtils.scala:821)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:929)
	at org.apache.spark.rdd.RDD$$anonfun$foreachPartition$1$$anonfun$apply$29.apply(RDD.scala:929)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
	at org.apache.spark.SparkContext$$anonfun$runJob$5.apply(SparkContext.scala:2074)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Some people said this is guava's issue:  https://stackoverflow.com/a/48234536
so, I debug it:
```scala
val jdbcDriverClass = Class.forName(jdbcDriver)
val guavaClass = Class.forName("com.google.common.escape.Escapers")
```
it seems all other jars works very well, but guava not.
```
Name: java.lang.ClassNotFoundException
Message: com.google.common.escape.Escapers
StackTrace:   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
```

if you google with `Scala 2.11.8  can not  guava` you will get a lot of such issue. 
So, guava introduce an issue, that disable clickhouse-jdbc

**Comment by tkroman** [comment]
should be addressed when this is merged https://github.com/yandex/clickhouse-jdbc/pull/194.
or you can try to build your own shaded jar.
or try experimenting with sbt's assembly rules: https://github.com/sbt/sbt-assembly#shading

**Comment by tkroman** [comment]
In general I think this is not a clickhouse-jdbc issue (besides the need to build shaded jar), this is one of these pains spark developers traditionally experience.

**Comment by Yensan** [comment]
OK, thanks. I will check it.  Will you release it soon?
I am a python developer, not familiar with java&sbt, so it confused and depressed me.

**Comment by tkroman** [comment]
I’m not a part of the team-owner if this repository, can’t give you estimates.

**Comment by serebrserg** [comment]
Please check shaded jar in 0.1.45

**Comment by zhicwu** [comment]
Close since the issue has been fixed for a while.
