### ISSUE TITLE
Execute batch doesn't work for new "delete" syntax

### ISSUE THREAD

**Issue by doom369** [ClickHouse/clickhouse-jdbc#296]
Query:

`ALTER TABLE reporting_average_minute delete WHERE device_id = ?`

```
try (PreparedStatement deleteQuery = connection.prepareStatement(query)) {
       deleteQuery.setInt(1, deviceId);
       deleteQuery.addBatch();
       deleteQuery.executeBatch();
}

```
could no be executed in the batch due to error:

```
java.sql.SQLSyntaxErrorException: Query must be like 'INSERT INTO [db.]table [(c1, c2, c3)] VALUES (?, ?, ?)'. Got: ALTER TABLE reporting_average_minute delete WHERE device_id = ?
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:355) ~[clickhouse-jdbc-0.1.50.jar:?]
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:348) ~[clickhouse-jdbc-0.1.50.jar:?]

```

**Comment by aimhighmp** [comment]
Hi.. We are also experiencing same issue? Is there plan to update JDBC API to support Delete/Alter with PreparedStatement? 
Thanks
