### ISSUE TITLE
Array support

### ISSUE THREAD

**Issue by morozovsk** [ClickHouse/clickhouse-jdbc#323]
I've created two tickets for [DataGrip](https://youtrack.jetbrains.com/issue/DBE-8042?p=WI-45981) and [dbeaver](https://github.com/dbeaver/dbeaver/issues/5598) but now I think it's your problem. Its both have your jdbc driver and Its both have problems with Array(Float32) and Array(Array(String)).

I have this structure:
```sql
create table pinba.requests
(
   ...,
  `tags.name`       Array(String),
  `tags.value`      Array(String),
  `timers.hitCount` Array(UInt32),
  `timers.value`    Array(Float32),
  `timers.tagName`  Array(Array(String)),
  `timers.tagValue` Array(Array(String)),
)
```
It has problems in DataGrip:
![screen299](https://user-images.githubusercontent.com/1822063/55118416-ea06c580-50f6-11e9-9013-78b8a4eb8e88.png)

And it has problems in dbeaver:
![screen300](https://user-images.githubusercontent.com/1822063/55118361-a9a74780-50f6-11e9-8f40-8fccde782be2.png)

But I don't have problems with http interface:
![screen298](https://user-images.githubusercontent.com/1822063/55118612-8fba3480-50f7-11e9-86c6-b2ab7a198a83.png)

clickhouse version - 19.4.1.1

Logs from dbeaver:
---

org.jkiss.dbeaver.model.exec.DBCException: Can't extract array data from Java array
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromJavaArray(JDBCCollection.java:289)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:66)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCArrayValueHandler.getValueFromObject(JDBCArrayValueHandler.java:1)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:50)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:204)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1679)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.jkiss.dbeaver.model.exec.DBCException: Can't resolve array element data type
	at org.jkiss.dbeaver.model.impl.jdbc.data.JDBCCollection.makeCollectionFromJavaArray(JDBCCollection.java:281)
	... 11 more

---

java.lang.RuntimeException: Parse exception: ByteFragment{[5d11a1771557<TAB><TAB>200<TAB>qweqewqweqewqweqweqweqew<TAB>xy/abcdef<TAB>0.072165<TAB>1499<TAB>6291456<TAB>3661824<TAB>0.027523<TAB>['country','os']<TAB>['us','ios']<TAB>[1,1,1,1]<TAB>[0.053563,15,10,11]<TAB>[['redis'],['redis2','redis4'],['redis3'],['false3','redis3']]<TAB>[['true'],['false','false4'],['false3'],['2','1']]<TAB>0000-00-00 00:00:00], start=152, len=62}
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getObject(ClickHouseResultSet.java:470)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:635)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:49)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:204)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1679)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalStateException
	at ru.yandex.clickhouse.response.ByteFragmentUtils.parseArray(ByteFragmentUtils.java:267)
	at ru.yandex.clickhouse.response.ByteFragmentUtils.parseArray(ByteFragmentUtils.java:154)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getArray(ClickHouseResultSet.java:299)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getObject(ClickHouseResultSet.java:461)
	... 10 more

---

java.lang.RuntimeException: Parse exception: ByteFragment{[5d11a1771557<TAB><TAB>200<TAB>qweqewqweqewqweqweqweqew<TAB>xy/abcdef<TAB>0.072165<TAB>1499<TAB>6291456<TAB>3661824<TAB>0.027523<TAB>['country','os']<TAB>['us','ios']<TAB>[1,1,1,1]<TAB>[0.053563,15,10,11]<TAB>[['redis'],['redis2','redis4'],['redis3'],['false3','redis3']]<TAB>[['true'],['false','false4'],['false3'],['2','1']]<TAB>0000-00-00 00:00:00], start=215, len=50}
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getObject(ClickHouseResultSet.java:470)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCResultSetImpl.getObject(JDBCResultSetImpl.java:635)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCComplexValueHandler.fetchColumnValue(JDBCComplexValueHandler.java:49)
	at org.jkiss.dbeaver.model.impl.jdbc.data.handlers.JDBCAbstractValueHandler.fetchValueObject(JDBCAbstractValueHandler.java:49)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetDataReceiver.fetchRow(ResultSetDataReceiver.java:122)
	at org.jkiss.dbeaver.model.impl.jdbc.struct.JDBCTable.readData(JDBCTable.java:204)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:102)
	at org.jkiss.dbeaver.model.DBUtils.tryExecuteRecover(DBUtils.java:1679)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:100)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:102)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.IllegalStateException
	at ru.yandex.clickhouse.response.ByteFragmentUtils.parseArray(ByteFragmentUtils.java:267)
	at ru.yandex.clickhouse.response.ByteFragmentUtils.parseArray(ByteFragmentUtils.java:154)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getArray(ClickHouseResultSet.java:299)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getObject(ClickHouseResultSet.java:461)
	... 10 more

---
Log from DataGrip:

java.lang.RuntimeException: Parse exception: ByteFragment{[5d11a1771557<TAB><TAB>200<TAB>qweqewqweqewqweqweqweqew<TAB>qw/asd1st<TAB>0.072165<TAB>1499<TAB>6291456<TAB>3661824<TAB>0.027523<TAB>['country','os']<TAB>['us','ios']<TAB>[1,1,1,1]<TAB>[0.053563,15,10,11]<TAB>[['redis'],['redis2','redis4'],['redis3'],['false3','redis3']]<TAB>[['true'],['false','false4'],['false3'],['2','1']]<TAB>0000-00-00 00:00:00], start=152, len=62}
at ru.yandex.clickhouse.response.ClickHouseResultSet.getObject(ClickHouseResultSet.java:458)
at com.intellij.database.remote.jdbc.helpers.JdbcHelperImpl.getObject(JdbcHelperImpl.java:304)
at com.intellij.database.remote.jdbc.helpers.JdbcHelperImpl.getObject(JdbcHelperImpl.java:257)
at com.intellij.database.remote.jdbc.helpers.JdbcHelperImpl.getCurrentRow(JdbcHelperImpl.java:242)
at com.intellij.database.remote.jdbc.impl.RemoteResultSetImpl.getObjects(RemoteResultSetImpl.java:1345)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
at sun.rmi.transport.Transport$1.run(Transport.java:200)
at sun.rmi.transport.Transport$1.run(Transport.java:197)
at java.security.AccessController.doPrivileged(Native Method)
at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
at java.security.AccessController.doPrivileged(Native Method)
at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException
at ru.yandex.clickhouse.response.ByteFragmentUtils.parseArray(ByteFragmentUtils.java:241)
at ru.yandex.clickhouse.response.ByteFragmentUtils.parseArray(ByteFragmentUtils.java:155)
at ru.yandex.clickhouse.response.ClickHouseResultSet.getArray(ClickHouseResultSet.java:292)
at ru.yandex.clickhouse.response.ClickHouseResultSet.getObject(ClickHouseResultSet.java:454)
... 21 more

**Comment by Blackmorse** [comment]
There is my PR for supporting array of arrays,
but for some reason It wasn't merged 
https://github.com/yandex/clickhouse-jdbc/pull/342

**Comment by zhicwu** [comment]
`select [['abc', '123'], ['efg', '456']] as test_array` works in DBeaver now, but there's still display issue for `select [[['a', '1'], ['b', '2']], [['c', '3'], ['d', '4']]] as test_array`.

Anyway, the driver has been rewritten since 0.3.2. Cases like `Array(Array(Array(Array(Array(Map(LowCardinality(String), Tuple(Array(UInt8),LowCardinality(String))))))))` are all supported although it's a bit slow. asm/bytebuddy, unsafe ByteUtils, Vector API etc. will be added in future releases to improve performance.
