### ISSUE TITLE
ClickHouseRowBinaryInputStream read FixedString(n)

### ISSUE THREAD

**Issue by ayudovin** [ClickHouse/clickhouse-jdbc#394]
I have table with `FixedString(10)` column. When I try to read using `ClickHouseRowBinaryInputStream.readString()` this column from a table I get the `exception.`

For example, my value is "0101712189" and I got 

`Caused by: java.io.EOFException
	at com.google.common.io.LittleEndianDataInputStream.readUnsignedByte(LittleEndianDataInputStream.java:83)
	at com.google.common.io.LittleEndianDataInputStream.readByte(LittleEndianDataInputStream.java:206)
	at ru.yandex.clickhouse.util.ClickHouseRowBinaryInputStream.readUnsignedLeb128(ClickHouseRowBinaryInputStream.java:41)
	at ru.yandex.clickhouse.util.ClickHouseRowBinaryInputStream.readString(ClickHouseRowBinaryInputStream.java:80)
	at com.badoo.Example.lambda$static$8f1f73c9$1(Example.java:35)
	at com.badoo.rdd.ClickHouseBinaryRdd$1.read(ClickHouseBinaryRdd.java:91)
	at com.badoo.rdd.ClickHouseBinaryIterator.next(ClickHouseBinaryIterator.java:46)
`

**Comment by ayudovin** [comment]
close due to pull request was merged
