### ISSUE TITLE
ClickHouse JDBC behind load balancer using SSL

### ISSUE THREAD

**Issue by martenlindblad** [ClickHouse/clickhouse-jdbc#420]
When connecting via clickhouse-jdbc version 0.2.3 I get the following stack trace:
```
Exception in thread "main" java.lang.RuntimeException: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: clickhouse.foo.bar, port: 443; <html><body><b>Http/1.1 Service Unavailable</b></body> </html>
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.initTimeZone(ClickHouseConnectionImpl.java:99)
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:80)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:55)
	at ru.yandex.clickhouse.ClickHouseDataSource.getConnection(ClickHouseDataSource.java:44)
	at ru.yandex.clickhouse.ClickHouseConnectionTest.main(ClickHouseConnectionTest.java:29)
Caused by: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: clickhouse.foo.bar, port: 443; <html><body><b>Http/1.1 Service Unavailable</b></body> </html>
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:91)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:55)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:875)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:616)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:117)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:100)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:95)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:90)
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.initTimeZone(ClickHouseConnectionImpl.java:94)
	... 4 more
Caused by: java.lang.Throwable: <html><body><b>Http/1.1 Service Unavailable</b></body> </html>
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:53)
	... 12 more
```

The response body is as follows:

`HTTP/1.1 503 Service Unavailable [Content-Length: 62, Connection: close, Cache-Control: no-cache,no-store, Pragma: no-cache] ResponseEntityProxy{[Content-Length: 62,Chunked: false]}`

Other client tools using the http connection works, such as pythons infi.clickhouse_orm

**Comment by martenlindblad** [comment]
It was an issue at the load balancer (netscaler). If we also add the specific hostname and port it works with apache httpclient:
`HTTP.REQ.HOSTNAME.EQ("clickhouse.example.com")||HTTP.REQ.HOSTNAME.EQ("clickhouse.example.com:443")`

**Comment by arthurdk** [comment]
Hello @martenlindblad, what kind of issues did you encounter? It seems I'm having the exact same behavior.

**Comment by martenlindblad** [comment]
Couldn't connect via the jdbc but with other http client tools.
