### ISSUE TITLE
kettle ETL tools  cannot connect clickhouse

### ISSUE THREAD

**Issue by Cpanmac** [ClickHouse/clickhouse-jdbc#444]
clickhouse-jdbc-jar：clickhouse-jdbc-0.2.4.jar
error logs：
Driver class 'ru.yandex.clickhouse.ClickHouseDriver' could not be found, make sure the 'Generic database' driver (jar file) is installed.
org/slf4j/LoggerFactory

	at org.pentaho.di.core.database.Database.connectUsingClass(Database.java:500)
	at org.pentaho.di.core.database.Database.normalConnect(Database.java:410)
	... 55 more
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at ru.yandex.clickhouse.ClickHouseDriver.<clinit>(ClickHouseDriver.java:31)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.pentaho.di.core.database.Database.connectUsingClass(Database.java:496)
	... 56 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 60 more

**Comment by Cpanmac** [comment]
To build a jar with dependencies use
mvn package assembly:single -DskipTests=true
