### ISSUE TITLE
Batch insertion failed when using Enum field

### ISSUE THREAD

**Issue by pavigor** [ClickHouse/clickhouse-jdbc#487]
Hi all. I have an issue with batch insertion to the table which has Enum field. When using batch mode INT field converting to String, I don't know why.

Here is the simple table:
```
CREATE TABLE EnumTest.Test
(
    `timestamp` UInt64,
    `uid` String,
    `type` Enum8('OK' = 0, 'FAILED' = 1)
)
ENGINE = MergeTree()
ORDER BY uid
SETTINGS index_granularity = 8192
```

And here is the simple Java code to reproduce the issue:

```
        String dbQuery = "CREATE DATABASE IF NOT EXISTS EnumTest";
        String tableQuery = "CREATE TABLE IF NOT EXISTS EnumTest.Test (\n" +
                "`timestamp` UInt64,\n" +
                "`uid` String,\n" +
                "`type` Enum('OK' = 0, 'FAILED' = 1)\n" +
                ")\n" +
                "ENGINE = MergeTree()\n" +
                "ORDER BY uid\n";
        try {
            ClickHouseConnectionImpl connection = (ClickHouseConnectionImpl) dataSource.getConnection();
            connection.setAutoCommit(true);
            // Create DB
            connection.createStatement().executeQuery(dbQuery);
            connection.setCatalog("EnumTest");
            // Create table
            connection.createStatement().executeQuery(tableQuery);

            // Batch insertion
            String query = "INSERT INTO Test (timestamp, uid, type) VALUES (?, ?, ?)";
            PreparedStatement statement = connection.prepareStatement(query);
            for (int i = 0; i < 10; i++) {
                statement.setLong(1, System.currentTimeMillis());
                statement.setString(2, UUID.randomUUID().toString());
                int type = (i % 2 == 0) ? 0 : 1;
                // ######## Insert integer ##########
                statement.setInt(3, type);
                statement.addBatch();
            }
            statement.executeBatch();
            statement.close();
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
```

**Issue:** 
```
ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 36, host: 172.17.0.2, port: 8123; Code: 36, e.displayText() = DB::Exception: Unknown element '0' for type Enum8('OK' = 0, 'FAILED' = 1) (version 20.6.4.44 (official build))

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:58)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:875)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:851)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:824)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:817)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:335)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:320)
```

**Comment by den-crane** [comment]
use String representation of Enum --   statement.setString(3, "OK");
or don't use executeBatch  -- use extended-api https://github.com/ClickHouse/clickhouse-jdbc#extended-api
