### ISSUE TITLE
ClickHouseRowBinaryStream.writeString throw ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by haiwenzhu** [ClickHouse/clickhouse-jdbc#516]
**version**: 0.2.4
**Stacktrace**:
java.lang.ArrayIndexOutOfBoundsException: 2048
	at org.apache.http.impl.io.ChunkedOutputStream.write(ChunkedOutputStream.java:153) 
	at java.io.DataOutputStream.write(DataOutputStream.java:88) 
	at java.io.FilterOutputStream.write(FilterOutputStream.java:77) 
	at ru.yandex.clickhouse.util.ClickHouseRowBinaryStream.writeUnsignedLeb128(ClickHouseRowBinaryStream.java:50) 
	at ru.yandex.clickhouse.util.ClickHouseRowBinaryStream.writeString(ClickHouseRowBinaryStream.java:78)

**Comment by haiwenzhu** [comment]
#515
