### ISSUE TITLE
 How to use BalancedClickhouseDataSource in flink sql?

### ISSUE THREAD

**Issue by tangxueming** [ClickHouse/clickhouse-jdbc#678]
[BalancedClickhouseDataSource.java](https://github.com/ClickHouse/clickhouse-jdbc/blob/master/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/BalancedClickhouseDataSource.java)
It work ok when I  set:
WITH (
    'connector' = 'jdbc',
    'url' = 'jdbc:clickhouse://192.168.1.1:8123/xx',
    'table-name' = 'table',
    'driver' = 'ru.yandex.clickhouse.ClickHouseDriver',
    'username' = 'user',
    'password' ='password'
);

It don't work when I set:
WITH (
    'connector' = 'jdbc',
   url' = 'jdbc:clickhouse://192.168.1.1:8123,192.168.1.2:8123,192.168.1.3:8123/xx',
    'table-name' = 'table',
    'driver' = 'ru.yandex.clickhouse.ClickHouseDriver',
    'username' = 'user',
    'password' ='password'
);
How do I tell flink to use the blanced jdbc?
Thanks!

**Comment by tangxueming** [comment]
java.io.IOException: unable to open JDBC writer
	at org.apache.flink.connector.jdbc.internal.AbstractJdbcOutputFormat.open(AbstractJdbcOutputFormat.java:72) ~[flink-connector-jdbc_2.11-1.12-SNAPSHOT.jar:1.12-SNAPSHOT]
	at org.apache.flink.connector.jdbc.internal.JdbcBatchingOutputFormat.open(JdbcBatchingOutputFormat.java:114) ~[flink-connector-jdbc_2.11-1.12-SNAPSHOT.jar:1.12-SNAPSHOT]
	at org.apache.flink.streaming.api.functions.sink.OutputFormatSinkFunction.open(OutputFormatSinkFunction.java:65) ~[flink-dist_2.11-1.12.0.jar:1.12-SNAPSHOT]
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36) ~[pupu_stream_sql_2021062305.jar:?]
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102) ~[flink-dist_2.11-1.12.0.jar:1.12-SNAPSHOT]
	at org.apache.flink.table.runtime.operators.sink.SinkOperator.open(SinkOperator.java:63) ~[flink-table-blink_2.11-1.12.0.jar:1.12-SNAPSHOT]
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:401) ~[flink-dist_2.11-1.12.0.jar:1.12-SNAPSHOT]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$2(StreamTask.java:507) ~[flink-dist_2.11-1.12.0.jar:1.12-SNAPSHOT]
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:92) ~[flink-dist_2.11-1.12.0.jar:1.12-SNAPSHOT]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:501) ~[flink-dist_2.11-1.12.0.jar:1.12-SNAPSHOT]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:531) ~[flink-dist_2.11-1.12.0.jar:1.12-SNAPSHOT]
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:722) ~[pupu_stream_sql_2021062305.jar:?]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:547) ~[pupu_stream_sql_2021062305.jar:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_265]
Caused by: java.lang.IllegalArgumentException: port is missed or wrong
	at ru.yandex.clickhouse.ClickhouseJdbcUrlParser.parseClickhouseUrl(ClickhouseJdbcUrlParser.java:42) ~[clickhouse-jdbc-0.2.4.jar:?]
	at ru.yandex.clickhouse.ClickhouseJdbcUrlParser.parse(ClickhouseJdbcUrlParser.java:30) ~[clickhouse-jdbc-0.2.4.jar:?]
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:69) ~[clickhouse-jdbc-0.2.4.jar:?]
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:55) ~[clickhouse-jdbc-0.2.4.jar:?]
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:47) ~[clickhouse-jdbc-0.2.4.jar:?]
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:29) ~[clickhouse-jdbc-0.2.4.jar:?]
	at java.sql.DriverManager.getConnection(DriverManager.java:664) ~[?:1.8.0_265]
	at java.sql.DriverManager.getConnection(DriverManager.java:247) ~[?:1.8.0_265]
	at org.apache.flink.connector.jdbc.internal.connection.SimpleJdbcConnectionProvider.getConnection(SimpleJdbcConnectionProvider.java:123) ~[flink-connector-jdbc_2.11-1.12-SNAPSHOT.jar:1.12-SNAPSHOT]
	at org.apache.flink.connector.jdbc.internal.AbstractJdbcOutputFormat.establishConnection(AbstractJdbcOutputFormat.java:77) ~[flink-connector-jdbc_2.11-1.12-SNAPSHOT.jar:1.12-SNAPSHOT]
	at org.apache.flink.connector.jdbc.internal.AbstractJdbcOutputFormat.open(AbstractJdbcOutputFormat.java:70) ~[flink-connector-jdbc_2.11-1.12-SNAPSHOT.jar:1.12-SNAPSHOT]
	... 13 mor

**Comment by zhicwu** [comment]
@tangxueming, `BalancedClickhouseDataSource.java` is a DataSource, but Flink uses DriverManager to get connection(see https://issues.apache.org/jira/browse/FLINK-17294). We probably should enhance the driver to support multiple endpoints specified in connection string.

**Comment by tangxueming** [comment]
@zhicwu 
thanks
