### ISSUE TITLE
Got NPE inside ClickHouseResultSet.toString when LogProxy is enabled

### ISSUE THREAD

**Issue by volyx** [ClickHouse/clickhouse-jdbc#683]
It looks like field `ru.yandex.clickhouse.response.ClickHouseResultSet#dateTimeTimeZone` can be null in some conditions

```
java.lang.NullPointerException: null
  at ru.yandex.clickhouse.response.ClickHouseResultSet.toString(ClickHouseResultSet.java:824) ~[clickhouse-jdbc-0.3.1.jar:0.3.1]
  at java.lang.String.valueOf(String.java:2951) ~[?:?]
  at java.lang.StringBuilder.append(StringBuilder.java:168) ~[?:?]
  at ru.yandex.clickhouse.util.LogProxy.invoke(LogProxy.java:53) ~[clickhouse-jdbc-0.3.1.jar:0.3.1]
  at com.sun.proxy.$Proxy48.executeQuery(Unknown Source) ~[?:?]
  at ru.yandex.clickhouse.ClickHouseConnectionImpl.initConnection(ClickHouseConnectionImpl.java:91) ~[clickhouse-jdbc-0.3.1.jar:0.3.1]
  at ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:78) ~[clickhouse-jdbc-0.3.1.jar:0.3.1]
  at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:62) ~[clickhouse-jdbc-0.3.1.jar:0.3.1]
  at ru.yandex.clickhouse.BalancedClickhouseDataSource.ping(BalancedClickhouseDataSource.java:144) [clickhouse-jdbc-0.3.1.jar:0.3.1]
  ```

**Comment by phoesh** [comment]
#682 Look at it.

**Comment by zhicwu** [comment]
Thanks @volyx for reporting the issue. It's not supposed to be null. What's the output of `select timezone()` on your server? We can add null check when constructing result set and be more defensive in resultset.toString method, but it's better to find the root case.

@phoesh, the pull request is incorrect but I got your point. Are you suffering the same issue? What will you get from `select timezone()`? `TimeZone.getTimeZone()` is not supposed to return a null value but we can add a check there to enforce UTC will be used when things go wrong.

**Comment by phoesh** [comment]
@zhicwu I was suffering this issue. I have checked the null value is returning here  ru.yandex.clickhouse.ClickHouseStatementImpl.updateResult getConnection().getTimeZone(). And why it will get null value?
See ru.yandex.clickhouse.ClickHouseConnectionImpl.initConnection try (Statement s = createStatement(); ResultSet rs = s.executeQuery("select timezone(), version()")). This createStatement() method construct the connection but the timezone is not set in the connection object. So it executes the query and ResultSet.toString appending ru.yandex.clickhouse.response.ClickHouseResultSet#dateTimeTimeZone string will throw this NPE.

**Comment by zhicwu** [comment]
Hahaha... good catch :) Fortunately this issue does not exist in the upcoming new client. I'll fix this over the weekend.
