### ISSUE TITLE
Failed to parse SETTINGS for batch insert

### ISSUE THREAD

**Issue by kusaeva** [ClickHouse/clickhouse-jdbc#745]
Hi! 
It seems something went wrong with parsing SETTINGS inside a batch INSERT query.
I've got a table
```
CREATE TABLE IF NOT EXISTS test
(
    `num` Int32
)
ENGINE = MergeTree
ORDER BY num
SETTINGS index_granularity = 8192
```
and batch insert
```
val sql = "insert into `test` (num) values (?) SETTINGS input_format_null_as_default = 1"
val stmt2 = conn.prepareStatement(sql)
stmt2.setObject(1, null);
stmt2.addBatch()
stmt2.executeBatch()
```

With clickhouse-jdbc v0.2.6 I got a warning with ParseException but the query was executed.

```
[2021-10-13 12:34:13,177] WARN  r.y.c.j.parser.ClickHouseSqlParser       [] Failed to parse the given SQL. If you believe the SQL is valid, please feel free to open an issue on Github with the following SQL and exception attached.
insert into `test` (num) values (?) SETTINGS input_format_null_as_default = 1
ru.yandex.clickhouse.jdbc.parser.ParseException: Parse error at line 1, column 37.  Encountered: SETTINGS
	at ru.yandex.clickhouse.jdbc.parser.ClickHouseSqlParser.generateParseException(ClickHouseSqlParser.java:8935)
	at ru.yandex.clickhouse.jdbc.parser.ClickHouseSqlParser.jj_consume_token(ClickHouseSqlParser.java:8870)
	at ru.yandex.clickhouse.jdbc.parser.ClickHouseSqlParser.sql(ClickHouseSqlParser.java:159)
	at ru.yandex.clickhouse.jdbc.parser.ClickHouseSqlParser.parse(ClickHouseSqlParser.java:100)
	at ru.yandex.clickhouse.jdbc.parser.ClickHouseSqlParser.parse(ClickHouseSqlParser.java:83)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.parseSingleStatement(ClickHouseStatementImpl.java:109)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.<init>(ClickHousePreparedStatementImpl.java:69)
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.createPreparedStatement(ClickHouseConnectionImpl.java:152)
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.prepareStatement(ClickHouseConnectionImpl.java:202)
	at vertis.pipeline.sandbox.ClickhouseDebugLab$.$anonfun$jdbcTest$1(ClickhouseDebugLab.scala:135)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:398)
	at zio.internal.FiberContext.$anonfun$fork$17(FiberContext.scala:770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

With v0.3.1-patch the warning is still here but now I got ClickHouseException too and query fails
```
[2021-10-13 12:39:21,488] WARN  r.y.c.j.parser.ClickHouseSqlParser       [] Parse error at line 1, column 37.  Encountered: SETTINGS. If you believe the SQL is valid, please feel free to open an issue on Github with this warning and the following SQL attached.
insert into `test` (num) values (?) SETTINGS input_format_null_as_default = 1
[2021-10-13 12:39:21,489] WARN  r.y.c.ClickHousePreparedStatementImpl    [] PreparedStatement will slow down non-INSERT queries, so please consider to use Statement instead.
Fiber failed.
An unchecked error was produced.
ru.yandex.clickhouse.except.ClickHouseException: ClickHouse exception, code: 27, host: localhost, port: 8123; Code: 27, e.displayText() = DB::ParsingException: Cannot parse input: expected '(' before: 'SETTINGS input_format_null_as_default = 1':  at row 1 (version 21.8.4.51 (official build))

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:59)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:29)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:1099)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:778)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeStatement(ClickHouseStatementImpl.java:256)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeBatch(ClickHouseStatementImpl.java:594)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:388)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:364)
	at vertis.pipeline.sandbox.ClickhouseDebugLab$.$anonfun$jdbcTest$1(ClickhouseDebugLab.scala:138)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:398)
	at zio.internal.FiberContext.$anonfun$fork$17(FiberContext.scala:770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.Throwable: Code: 27, e.displayText() = DB::ParsingException: Cannot parse input: expected '(' before: 'SETTINGS input_format_null_as_default = 1':  at row 1 (version 21.8.4.51 (official build))

	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:54)
```

It looks like this was caused by this [change](https://github.com/ClickHouse/clickhouse-jdbc/commit/298c2abdf0cf4d1fe7aee8bb56d3adedb91956be
) but I am not really sure

I tested it with
```
ClickHouse client version 21.9.4.35 (official build).
Connected to ClickHouse server version 21.8.4 revision 54449.
```

**Comment by kusaeva** [comment]
Got it, thanks! I have to downgrade to 0.2.6, not sure if this setting could be set in a separate statement, looks like it should be set for a query ([doc](https://clickhouse.com/docs/en/operations/settings/settings/#settings-input-format-null-as-default))

**Comment by zhicwu** [comment]
It's supported in 0.3.2.
