### ISSUE TITLE
spark write bitmap failed when use 0.3.0 version

### ISSUE THREAD

**Issue by fantasticKe** [ClickHouse/clickhouse-jdbc#748]
An error occurred when I used Spark2.4.7 to write a bitmap to clickhouse：

java.lang.NoSuchMethodError: org.roaringbitmap.RoaringBitmap.serialize(Ljava/nio/ByteBuffer;)V
	at ru.yandex.clickhouse.util.ClickHouseBitmap$ClickHouseRoaringBitmap.serialize(ClickHouseBitmap.java:37)
	at ru.yandex.clickhouse.util.ClickHouseBitmap.toByteBuffer(ClickHouseBitmap.java:517)
	at ru.yandex.clickhouse.util.ClickHouseRowBinaryStream.writeBitmap(ClickHouseRowBinaryStream.java:362)

my code:
val statement = connection.createStatement
          try statement.sendRowBinaryStream(chInsertSql, new ClickHouseStreamCallback() {
            override def writeTo(clickHouseRowBinaryStream: ClickHouseRowBinaryStream): Unit = {
              msgIterator.foreach(data => {
                clickHouseRowBinaryStream.writeUInt32(ds)
                clickHouseRowBinaryStream.writeString(data.getAs[String]("name"))
                clickHouseRowBinaryStream.writeString(data.getAs[String]("value"))
                val idArray = data.getAs[Seq[Int]]("id_array")
                val bitmap: RoaringBitmap = RoaringBitmap.bitmapOf(idArray: _*)
                clickHouseRowBinaryStream.writeBitmap(ClickHouseBitmap.wrap(bitmap, ClickHouseDataType.UInt32))
              })
            }
          })
          finally if (statement != null) statement.close()

**Comment by fantasticKe** [comment]
i got it
