### ISSUE TITLE
spirngboot集成启动报错 Method threw java.lang.NullPointerException

### ISSUE THREAD

**Issue by fahualei** [ClickHouse/clickhouse-jdbc#758]
ClickHouseConnectionImpl 连接实现类 91行 初始时间、版本查询时，后续LogProxy中有结果集toString调用， 但timezone此时还是null 会出现异常

**Comment by zhicwu** [comment]
Which version of the driver you're using? 0.3.1-patch? Will changing log level to WARN/ERROR help?

**Comment by fahualei** [comment]
是的，0.3.1-patch同样会这样。日志级别为TRACE时，个人debug判断为Logproxy该类在TRACE级别输出后，44行方法invoke会执行至msg+=invokeResult; 时则会报错。
2021-11-22 22:33:22.302 [Druid-ConnectionPool-Create-1794486854] TRACE ru.yandex.clickhouse.util.LogProxy - ==== ClickHouse JDBC trace begin ====
Call class: ru.yandex.clickhouse.ClickHouseStatementImpl
Method: executeQuery
Object: ***@***.***
Args: [select timezone(), version()]
Invoke result:&nbsp;
==== ClickHouse JDBC trace end ====
2021-11-22 22:33:22.302 [Druid-ConnectionPool-Create-1794486854] TRACE ru.yandex.clickhouse.util.LogProxy - ==== ClickHouse JDBC trace begin ====
Call class: ru.yandex.clickhouse.ClickHouseStatementImpl
Method: close
Object: ***@***.***
Args: null
Invoke result: null
==== ClickHouse JDBC trace end ====
2021-11-22 22:33:22.303 [Druid-ConnectionPool-Create-1794486854] ERROR com.alibaba.druid.pool.DruidDataSource - create connection RuntimeException
java.lang.NullPointerException: null
	at ru.yandex.clickhouse.response.ClickHouseResultSet.toString(ClickHouseResultSet.java:824) ~[clickhouse-jdbc-0.3.1-patch.jar:0.3.1-patch]
	at java.lang.String.valueOf(String.java:2951) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:168) ~[?:?]
	at ru.yandex.clickhouse.util.LogProxy.invoke(LogProxy.java:53) ~[clickhouse-jdbc-0.3.1-patch.jar:0.3.1-patch]
	at com.sun.proxy.$Proxy86.executeQuery(Unknown Source) ~[?:?]
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.initConnection(ClickHouseConnectionImpl.java:91) ~[clickhouse-jdbc-0.3.1-patch.jar:0.3.1-patch]
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.<init&gt;(ClickHouseConnectionImpl.java:78) ~[clickhouse-jdbc-0.3.1-patch.jar:0.3.1-patch]
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:62) ~[clickhouse-jdbc-0.3.1-patch.jar:0.3.1-patch]
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:54) ~[clickhouse-jdbc-0.3.1-patch.jar:0.3.1-patch]
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:36) ~[clickhouse-jdbc-0.3.1-patch.jar:0.3.1-patch]



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ClickHouse/clickhouse-jdbc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月22日(星期一) 晚上6:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ClickHouse/clickhouse-jdbc] spirngboot集成启动报错 Method threw java.lang.NullPointerException (Issue #758)





 
Which version of the driver you're using? 0.3.1-patch? Will changing log level to WARN/ERROR help?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zhicwu** [comment]
Could you increase log level for ru.yandex package? I've stopped patching the code for a while. In the new JDBC driver, `LogProxy` has been removed, and I took advice from #697 by adding new options to avoid additional query when initializing connection - something like below:
```java
ClickHouseConfig config = clientRequest.getConfig();
String currentDb = null;
String currentUser = null;
TimeZone timeZone = null;
ClickHouseVersion version = null;
if (config.hasServerInfo()) { // when both serverTimeZone and serverVersion are configured
    timeZone = config.getServerTimeZone();
    version = config.getServerVersion();
} else {
    try (ClickHouseResponse response = clientRequest.copy().option(ClickHouseClientOption.ASYNC, false)
            .option(ClickHouseClientOption.COMPRESS, false).option(ClickHouseClientOption.DECOMPRESS, false)
            .option(ClickHouseClientOption.FORMAT, ClickHouseFormat.RowBinaryWithNamesAndTypes)
            .query("select currentDatabase(), currentUser(), timezone(), version()").execute().get()) {
        ClickHouseRecord r = response.firstRecord();
        currentDb = r.getValue(0).asString();
        currentUser = r.getValue(1).asString();
        String tz = r.getValue(2).asString();
        String ver = r.getValue(3).asString();
        version = ClickHouseVersion.of(ver);
        if (ClickHouseChecker.isNullOrBlank(tz)) {
            tz = "UTC";
        }
        timeZone = "UTC".equals(tz) ? ClickHouseValues.UTC_TIMEZONE : TimeZone.getTimeZone(tz);
        ...
}
```

**Comment by fahualei** [comment]
我需要开启TRACE级别输出，尝试使用了0.2.6版本无该问题。好的，既然LogProxy新版本移除了，等新版发布后再尝试升级。

**Comment by zhicwu** [comment]
I think you can start to integrate with [0.3.2-test3](../releases/tag/v0.3.2-test3)(batch insertion is not supported very well). 0.3.2 will be released tonight or tomorrow, depending how long it took to run test against batch insertion.
