### ISSUE TITLE
Unable to connect with the v0.3.2-test2 driver due to ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by akilovich** [ClickHouse/clickhouse-jdbc#780]
Hi there.

I'm doing [this](https://github.com/dbeaver/dbeaver/issues/14771) ticket. I'm trying to connect to our Clickhouse using the v0.3.2-test2 driver to test the fix. However, I find no success in that because I encounter the following exception when I click Test Connection: 

```Java
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.clickhouse.client.data.ClickHouseTabSeparatedProcessor$Records$1.getValue(ClickHouseTabSeparatedProcessor.java:77)
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:173)
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:137)
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:145)
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:41)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.lambda$0(JDBCDataSource.java:184)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:203)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:136)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:103)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.initializeMainContext(JDBCRemoteInstance.java:100)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCRemoteInstance.<init>(JDBCRemoteInstance.java:59)
	at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeRemoteInstance(JDBCDataSource.java:111)
	at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:108)
	at org.jkiss.dbeaver.ext.generic.model.meta.GenericMetaModel.createDataSourceImpl(GenericMetaModel.java:89)
	at org.jkiss.dbeaver.ext.generic.GenericDataSourceProvider.openDataSource(GenericDataSourceProvider.java:106)
	at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:898)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
	at org.jkiss.dbeaver.runtime.jobs.ConnectJob.runSync(ConnectJob.java:98)
	at org.jkiss.dbeaver.ui.actions.datasource.DataSourceHandler.connectToDataSource(DataSourceHandler.java:113)
	at org.jkiss.dbeaver.ui.actions.datasource.UIServiceConnectionsImpl.initConnection(UIServiceConnectionsImpl.java:70)
	at org.jkiss.dbeaver.model.navigator.DBNDataSource.initializeNode(DBNDataSource.java:158)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:225)
	at org.jkiss.dbeaver.model.navigator.DBNDatabaseNode.getChildren(DBNDatabaseNode.java:1)
	at org.jkiss.dbeaver.model.navigator.DBNUtils.getNodeChildrenFiltered(DBNUtils.java:79)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:49)
	at org.jkiss.dbeaver.ui.navigator.database.load.TreeLoadService.evaluate(TreeLoadService.java:1)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:88)
	at org.jkiss.dbeaver.ui.LoadingJob.run(LoadingJob.java:72)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

I have no problems connecting to the same Clickhouse instance with the 0.2.6 driver. It looks like a driver issue to me. Can you help?

For more info: ClickHouse 20.4.4.18, the database is behind the SSH tunnel, port 8123, localhost, no password.

**Comment by zhicwu** [comment]
Thanks @akilovich. It seems you changed `format` to a text-based format like `TSV`? By default it should be `RowBinaryWithNamesAndTypes`. I'll publish `0.3.2-test3` tonight when I get home - you can use it if changing format to default still not working at your end.

FYI, in the latest version of the driver(not published yet), I changed default to use `HttpURLConnection` for accessing ClickHouse server and leave an option to allow user to switch to `HttpClient` as needed.

**Comment by zhicwu** [comment]
@akilovich , could you please use [active release](../../ClickHouse/pulls?q=is%3Aopen+is%3Apr+label%3Arelease) like 21.3 or above for testing?

**Comment by akilovich** [comment]
@zhicwu Yes, I've tried with the `clickhouse/clickhouse-server:latest` Docker image, works like a charm.

**Comment by zhicwu** [comment]
This happens when using test builds against ClickHouse server older than 20.7. I'm closing this one and will submit a pull request in dbeaver to bump the driver to latest.
