### ISSUE TITLE
error when connect to spark

### ISSUE THREAD

**Issue by zhulinyijulie** [ClickHouse/clickhouse-jdbc#802]
error came when I try to connect spark to clickhouse through jdbc:

scala> dfInsert.write.mode("overwrite").option("batchsize", "20000").option("isolationLevel", "NONE").option("numPartitions", "2").jdbc("jdbc:clickhouse://192.168.3.123:8124/default","test",pro)
java.lang.NoClassDefFoundError: com/clickhouse/client/config/ClickHouseOption
  at java.lang.Class.getDeclaredConstructors0(Native Method)
  at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
  at java.lang.Class.getConstructor0(Class.java:3075)
  at java.lang.Class.newInstance(Class.java:412)
  at org.apache.spark.sql.execution.datasources.jdbc.DriverRegistry$.register(DriverRegistry.scala:53)
  at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions$$anonfun$6.apply(JDBCOptions.scala:79)
  at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions$$anonfun$6.apply(JDBCOptions.scala:79)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:79)
  at org.apache.spark.sql.execution.datasources.jdbc.JDBCOptions.<init>(JDBCOptions.scala:35)
  at org.apache.spark.sql.execution.datasources.jdbc.JdbcRelationProvider.createRelation(JdbcRelationProvider.scala:60)
  at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:45)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
  at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
  at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
  at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
  at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
  at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
  at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:656)
  at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:656)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
  at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:656)
  at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:273)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:267)
  at org.apache.spark.sql.DataFrameWriter.jdbc(DataFrameWriter.scala:501)
  ... 49 elided
Caused by: java.lang.ClassNotFoundException: com.clickhouse.client.config.ClickHouseOption
  at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  ... 79 more

I already have jars:
clickhouse-jdbc-0.3.2.jar
clickhouse-http-client-0.3.2.jar
clickhouse-client-0.3.2.jar
gson-2.8.9.jar
httpclient-4.5.13.jar
httpmime-4.5.13.jar
lz4-java-1.8.0.jar

this is my code:
val pro = new java.util.Properties
pro.put("driver", "com.clickhouse.jdbc.ClickHouseDriver")
dfInsert.write
.mode("overwrite")
.option("batchsize", "20000")
.option("isolationLevel", "NONE")
.option("numPartitions", "2")
.jdbc("jdbc:clickhouse://192.168.3.123:8124/default","test",pro)

I donot know which jar is missing ,please help me
Thanks in advance.

**Comment by zhicwu** [comment]
Could you use shaded jar like `clickhouse-jdbc-0.3.2-http.jar`?

**Comment by zhulinyijulie** [comment]
> 
I solve it by using clickhouse-jdbc-0.3.2-all.jar，Thanks！

**Comment by zhicwu** [comment]
> I solve it by using clickhouse-jdbc-0.3.2-all.jar，Thanks！

Good to know. If you're experiencing issue of retrieving null date/datetime values, you may want to update to `0.3.2-patch1`.

**Comment by Aload** [comment]
> clickhouse-jdbc-0.3.2-all

Hey, friend.  I have the same problem, please tell me how you solve it.  Clickhouse - jdbC-0.3.2-all. jar not found

**Comment by swarupsarangi113** [comment]
You can find it from [here](https://github.com/ClickHouse/clickhouse-jdbc/releases)
