### ISSUE TITLE
CTE in INSERT INTO SELECT query triggers unexpected "Missing parameters" exception

### ISSUE THREAD

**Issue by Dnnd** [ClickHouse/clickhouse-jdbc#810]
I'm using clickhouse-jdbc `v0.3.2-patch1` with Clickhouse Server  v21.6.6.
The code snippet below:

```java
var ds = new ClickHouseDataSource(chURL, properties);
try (var conn = ds.getConnection()) {
      conn.prepareStatement("CREATE TABLE IF NOT EXISTS  target(value String) ENGINE Log").execute();
      conn.prepareStatement("INSERT INTO target(value) WITH t as ( SELECT 'testValue') SELECT * FROM  t").execute();
}
```
triggers an `SQLException` with the following exception message:

```
Exception in thread "main" java.sql.SQLException: Missing parameter(s): [1]
	at com.clickhouse.jdbc.SqlExceptionUtils.clientError(SqlExceptionUtils.java:42)
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.ensureParams(InputBasedPreparedStatement.java:87)
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.execute(InputBasedPreparedStatement.java:215)
```
If I remove CTE from the query, it executes without errors:

```java
var ds = new ClickHouseDataSource(chURL, properties);
try (var conn = ds.getConnection()) {
      conn.prepareStatement("CREATE TABLE IF NOT EXISTS  target(value String) ENGINE Log").execute();
      conn.prepareStatement("INSERT INTO target(value) SELECT 'testValue'").execute();
}
```

If I have at least one parameter, no exception is thrown as well:
```java
try (var conn = ds.getConnection()) {
      conn.prepareStatement("CREATE TABLE IF NOT EXISTS  target(value String) ENGINE Log").execute();
      var ps = conn.prepareStatement("INSERT INTO target(value) WITH t as ( SELECT 'testValue' as value)  SELECT * FROM t WHERE value != ?");
      ps.setString(1, "test");
      ps.execute();
}
```
This wasn't the case in the `v0.3.1` and it seems like a bug.

**Comment by Dnnd** [comment]
Nevermind, the problem wasn't related to the driver - I was using incorrect CTE syntax

**Comment by zhicwu** [comment]
Thanks for reporting the issue. Will fix it later today and release patch3 tomorrow or so.

**Comment by zy8las** [comment]
Has it been released

**Comment by zhicwu** [comment]
> Has it been released

Yes. If your CTE is complex, for instance it contains CASE WHEN, you'd better use parensises to group sub expressions.

**Comment by zhicwu** [comment]
> Has it been released

Yes. If your CTE is complex, for instance it contains CASE WHEN, you'd better use parensises to group sub expressions.
