### ISSUE TITLE
Clickhouse jdbc connection with maven

### ISSUE THREAD

**Issue by aamirbutt** [ClickHouse/clickhouse-jdbc#833]
I am trying to connect in a maven project and I am getting errors where It can apparently load the class but fails to connect:

```
  private static void connectClickhouse() {
    String url = "jdbc:ch://localhost/events";
    try {
      Class.forName("com.clickhouse.jdbc.ClickHouseDriver");
    } catch (ClassNotFoundException ex) {
      System.out.println("Could not load driver: " + ex.getMessage());
      return;
    }

    try {
      ClickHouseDataSource dataSource = new ClickHouseDataSource(url);
      Connection conn = dataSource.getConnection();
      conn.close();
    } catch (SQLException ex) {
      System.out.println(ex.getMessage());
    }
  }
```

I have following in pom.xml:
```
        <dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-jdbc</artifactId>
            <version>0.3.2-patch4</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.clickhouse/clickhouse-client -->
        <dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-client</artifactId>
            <version>0.3.2-patch4</version>
        </dependency>
        <!-- https://mvnrepository.com/artifact/com.clickhouse/clickhouse-java -->
        <dependency>
            <groupId>com.clickhouse</groupId>
            <artifactId>clickhouse-java</artifactId>
            <version>0.3.2-patch4</version>
            <type>pom</type>
        </dependency>
```

I am getting the following error on `getConnection`:
```
Exception in thread "main" java.lang.IllegalStateException: No suitable ClickHouse client(out of 1) found in classpath.
        at com.clickhouse.client.ClickHouseClientBuilder.build(ClickHouseClientBuilder.java:103)
        at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:227)
        at com.clickhouse.jdbc.ClickHouseDataSource.getConnection(ClickHouseDataSource.java:44)
        at zir.SqlLiteTest.connectClickhouse(SqlLiteTest.java:40)
        at zir.SqlLiteTest.main(SqlLiteTest.java:26)```
        

Any idea what else needs to be done?

**Comment by zhicwu** [comment]
Perhaps you can check examples at [here](../tree/master/examples/jdbc)?

**Comment by aamirbutt** [comment]
I am getting a similar error with the example that you shared. The only thing is that this error comes up when I run it from command-line by creating a jar file. I added this plugin to pom.xml to create a jar file with a mainClass.
```
            <plugin>
                <!-- Build an executable JAR -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <addClasspath>true</addClasspath>
                            <classpathPrefix>lib/</classpathPrefix>
                            <mainClass>com.clickhouse.examples.jdbc.Basic</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
```

The error I get when I run it like this: `java -jar .\target\jdbc-examples-1.0.0.jar` is :
```
java.sql.SQLException: No suitable driver found for jdbc:ch://localhost:8123/system
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
        at com.clickhouse.examples.jdbc.Basic.dropAndCreateTable(Basic.java:12)
        at com.clickhouse.examples.jdbc.Basic.main(Basic.java:81)```

It runs fine from my IDE though (which is intelliJ)

**Comment by zhicwu** [comment]
This is irrelevant to the driver.

In order to use the JDBC driver, please either create a shaded jar or include it in your classpath.
