### ISSUE TITLE
Is it support HTTPS protocol?

### ISSUE THREAD

**Issue by fsgdgsdfgsgd** [ClickHouse/clickhouse-jdbc#847]
Hi guys,

I tried to connect to my CH node through HTTP protocol and it was successful. Then I want to connect via HTTPS and change the port to 8443. But I encountered this error:
```
Caused by: com.clickhouse.client.ClickHouseException: Unexpected end of file from server, server ClickHouseNode(addr=http:xxx:8443, db=system)@1378242005
	at com.clickhouse.client.ClickHouseException.of(ClickHouseException.java:113) ~[clickhouse-client-0.3.2-patch5.jar:na]
	at com.clickhouse.client.http.ClickHouseHttpClient.lambda$execute$0(ClickHouseHttpClient.java:109) ~[clickhouse-http-client-0.3.2-patch5.jar:na]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]
Caused by: java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:866) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:863) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[na:na]
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527) ~[na:na]
	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:116) ~[clickhouse-http-client-0.3.2-patch5.jar:na]
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:201) ~[clickhouse-http-client-0.3.2-patch5.jar:na]
	at com.clickhouse.client.http.ClickHouseHttpClient.postRequest(ClickHouseHttpClient.java:88) ~[clickhouse-http-client-0.3.2-patch5.jar:na]
	at com.clickhouse.client.http.ClickHouseHttpClient.lambda$execute$0(ClickHouseHttpClient.java:107) ~[clickhouse-http-client-0.3.2-patch5.jar:na]
	... 4 common frames omitted
```
It seem that the library still use HTTP parser. Does this mean that currently this library does not support HTTPS connections?
But I noticed that there is configuration about ssl in ClickHouseConfig class.
Does anyone know about this? It would be very helpful! :)

**Comment by zhicwu** [comment]
Yes it supports https. You may need two connection properties:
* ssl=[true|false]
* sslmode=[NONE|STRICT]

You can specify in connection string as well, for example: `jdbc:ch://localhost:8443/?ssl=true&sslmode=NONE`

**Comment by fsgdgsdfgsgd** [comment]
I followed this sample to develop, should I switch to JDBC driver?
```
// only HTTP and gRPC are supported at this point
ClickHouseProtocol preferredProtocol = ClickHouseProtocol.HTTP;
// you'll have to parse response manually if use different format
ClickHouseFormat preferredFormat = ClickHouseFormat.RowBinaryWithNamesAndTypes;

// connect to localhost, use default port of the preferred protocol
ClickHouseNode server = ClickHouseNode.builder().port(preferredProtocol).build();

try (ClickHouseClient client = ClickHouseClient.newInstance(preferredProtocol);
    ClickHouseResponse response = client.connect(server)
        .format(preferredFormat)
        .query("select * from numbers(:limit)")
        .params(1000).execute().get()) {
    // or resp.stream() if you prefer stream API
    for (ClickHouseRecord record : resp.records()) {
        int num = record.getValue(0).asInteger();
        String str = record.getValue(0).asString();
    }

    ClickHouseResponseSummary summary = resp.getSummary();
    long totalRows = summary.getRows();
}
```

**Comment by zhicwu** [comment]
> should I switch to JDBC driver?

What's the use case? You should if you need stable API and don't care about overheads introduced in JDBC driver like SQL parsing and additional object creation. Or, if you prefer low-overhead and async calls, you may use Java client shown above.

**Comment by fsgdgsdfgsgd** [comment]
Sorry I didn't make it clear. Actually, I want to know how to set ssl through Java client, because I see your example is using JDBC driver.

**Comment by fsgdgsdfgsgd** [comment]
Oh I found it. I should use `ClickHouseRequest.option()` to set property. Very sorry! :)
