### ISSUE TITLE
[SQL Exception] com.clickhouse.client.ClickHouseConfig.getMaxResultRows()I

### ISSUE THREAD

**Issue by vumdao** [ClickHouse/clickhouse-jdbc#865]
Clickhouse version 21.3.14.1

Client driver: [ClickHouse JDBC](https://mvnrepository.com/artifact/com.clickhouse/clickhouse-jdbc) » [0.3.2-patch5](https://mvnrepository.com/artifact/com.clickhouse/clickhouse-jdbc/0.3.2-patch5)

`max_result_rows`
```
clh :) select * from system.settings where name in( 'max_result_rows')

SELECT *
FROM system.settings
WHERE name IN ('max_result_rows')

Query id: 642ac1ed-b6c7-4fd0-9959-41e5f2ce3fa0

┌─name────────────┬─value─┬─changed─┬─description────────────────────────────────────────────────────────────────────────────────┬─min──┬─max──┬─readonly─┬─type───┐
│ max_result_rows │ 0     │       0 │ Limit on result size in rows. Also checked for intermediate data sent from remote servers. │ ᴺᵁᴸᴸ │ ᴺᵁᴸᴸ │        0 │ UInt64 │
└─────────────────┴───────┴─────────┴────────────────────────────────────────────────────────────────────────────────────────────┴──────┴──────┴──────────┴────────┘

1 rows in set. Elapsed: 0.003 sec. 
```

Detailed Error Report
```
There was an error while processing your request.
--
Message:com.clickhouse.client.ClickHouseConfig.getMaxResultRows()I
```

**Comment by zhicwu** [comment]
Do you have more information like stack trace of the exception? Just tried the query on DBeaver but not able to reproduce.

**Comment by vumdao** [comment]
@zhicwu Full stack trace 
```
Stack Trace:
at rdServer.rdSqlReader.a(Unknown Source)
at rdServer.rdSqlReader.(Unknown Source)
at rdServer.rdDb.access$5100(Unknown Source)
at rdServer.rdDb.a(Unknown Source)
at rdServer.rdDb.c(Unknown Source)
at rdServer.rdDb.b(Unknown Source)
at rdServer.rdDb.xmlGetData(Unknown Source)
at rdServer.rdDb9.xmlGetData(Unknown Source)
at rdServer.rdState.subGetLocalData9(Unknown Source)
at rdServer.rdState.subGetReportStartupParams(Unknown Source)
at rdServer.PageBuilder.BuildHtml(Unknown Source)
at rdServer.ResponseBuilder.BuildResponse(Unknown Source)
at rdServer.ResponseBuilder.BuildResponse(Unknown Source)
at ASP.rdpage_aspx.__Render__control1(rdPage.aspx:4)
at ASP.rdpage_aspx$__Impl0.Invoke(Unknown Source)
at system.Web.UI.Control.RenderChildren(Control.cs:1101)
at system.Web.UI.Control.Render(Control.cs:1090)
at system.Web.UI.Page.Render(Page.cs:1095)
at system.Web.UI.Control.RenderControl(Control.cs:1254)
at system.Web.UI.Page.RenderPage(Page.cs:1621)
at system.Web.UI.Page.encodeChildren(Page.jvm.cs:159)
at Mainsoft.Web.Hosting.BaseFacesViewHandler.renderView(BaseFacesViewHandler.cs:61)
at org.apache.myfaces.lifecycle.RenderResponseExecutor.execute(RenderResponseExecutor.java:41)
at org.apache.myfaces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:132)
at Mainsoft.Web.Hosting.ServletFacesPageHandler.ProcessRequest(ServletFacesPageHandler.cs:116)
at Mainsoft.Web.Hosting.SessionWrapper$SessionWrapperHandler.ProcessRequest(SessionWrapper.cs:40)
at system.Web.HttpApplication$Pipelined__8.MoveNext$Z$$_$Pipeline$_$d__8$$(HttpApplication.cs:1033)
at system.Web.HttpApplication.Tick(HttpApplication.cs:705)
at system.Web.HttpApplication.Start(HttpApplication.cs:1217)
at system.Web.HttpApplication.System_Web_IHttpAsyncHandler_BeginProcessRequest(HttpApplication.cs:1319)
at system.Web.HttpRuntime.RealProcessRequest(HttpRuntime.cs:482)
at system.Web.HttpRuntime.ProcessRequest(HttpRuntime.cs:523)
at Mainsoft.Web.Hosting.BaseHttpServlet.service(BaseHttpServlet.cs:200)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:769)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:359)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:889)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:750)```

**Comment by zhicwu** [comment]
Thanks @vumdao but the stack trace seems irrelevant. Could you provide reproduce steps? Would be great if you can provide sample code in Java / SQL to reproduce the exact same error.
