### ISSUE TITLE
NPE when inserting BigDecimal values to Decimal(19,2)

### ISSUE THREAD

**Issue by PatrickTu** [ClickHouse/clickhouse-jdbc#881]
Hi, using `PreparedStatement`, I am attempting to insert `BigDecimal` values into `Decimal(19,2)` columns; it throws **NPE** when we attempt to write to `ClickHouseOutputStream`. Is this intended? 

If we construct the `INSERT INTO` statement with `NULL`, ClickHouse uses the defined default values.

**Table DDL and Inserts**

```sql
CREATE TABLE EXAMPLE_BIG_DECIMAL
(
    id      Int64,
    col1     Decimal(19, 2), -- Default is 0
    col2     Decimal(19, 2) DEFAULT -1 -- Default is -1
) ENGINE = MergeTree
      ORDER BY (id);

INSERT INTO EXAMPLE_BIG_DECIMAL (id, col1, col2)
VALUES 
(1, NULL, NULL) (2, 25.00, NULL) (3, 25.00, 25.45);
```

**Expected Rows**

| id   | col1  | col2  |
| :--- | :---- | :---- |
| 1    | 0.00  | -1.00 |
| 2    | 25.00 | -1.00 |
| 3    | 25.00 | 25.45 |

-----

**Exception**

```java
Caused by: java.lang.NullPointerException: Cannot read the array length because "value" is null
	at com.clickhouse.client.data.BinaryStreamUtils.writeString(BinaryStreamUtils.java:1661) ~[clickhouse-jdbc-0.3.2-patch6-http.jar:clickhouse-jdbc 0.3.2-patch6 (revision: 1d6257c)]
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$MappedFunctions.lambda$buildMappingsForDataTypes$65(ClickHouseRowBinaryProcessor.java:338) ~[clickhouse-jdbc-0.3.2-patch6-http.jar:clickhouse-jdbc 0.3.2-patch6 (revision: 1d6257c)]
	at com.clickhouse.client.data.ClickHouseRowBinaryProcessor$MappedFunctions.serialize(ClickHouseRowBinaryProcessor.java:485) ~[clickhouse-jdbc-0.3.2-patch6-http.jar:clickhouse-jdbc 0.3.2-patch6 (revision: 1d6257c)]
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.addBatch(InputBasedPreparedStatement.java:295) ~[clickhouse-jdbc-0.3.2-patch6-http.jar:clickhouse-jdbc 0.3.2-patch6 (revision: 1d6257c)]
```

**Code to reproduce exception**

Using `PreparedStatement`

```java
Object nullableValue = null;
Object nullableValueTwo = null;
...
preparedStatement.setObject(1, 1);
preparedStatement.setObject(2, nullableValue);
preparedStatement.setObject(3, nullableValueTwo);
preparedStatement.addBatch();
...
preparedStatement.executeBatch();
...
```

Isolating the exception to  `ClickHouseOutputStream`

```java
import com.clickhouse.client.data.ClickHouseBigDecimalValue;
import com.clickhouse.client.ClickHouseOutputStream;

OutputStream outputStream = ClickHouseOutputStream.nullOutputStream();
ClickHouseBigDecimalValue chbdv = ClickHouseBigDecimalValue.ofNull();
// Upstream values are passed in as Object
chbdv.update((Object) null);

try {
  BinaryStreamUtils.writeString(outputStream, chbdv.asBinary());
  } catch (Exception e) {
    e.printStackTrace();
}

```

```java
java.lang.NullPointerException: Cannot read the array length because "value" is null
	 at com.clickhouse.client.data.BinaryStreamUtils.writeString(BinaryStreamUtils.java:1661)
```

**Comment by zhicwu** [comment]
Thanks @PatrickTu, I think it's same issue as you reported in #878.
