### ISSUE TITLE
Cannot accept String as Enum8 value

### ISSUE THREAD

**Issue by marcioapm** [ClickHouse/clickhouse-jdbc#883]
Observed:
Calling `PreparedStatement.setObject` for a column of type `Enum8(0 = 'production', 1 = 'development')` with a String as parameter throws exception:
```
java.lang.NumberFormatException: For input string: "development"
	at java.base/java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.base/java.lang.Integer.parseInt(Unknown Source)
	at java.base/java.lang.Byte.parseByte(Unknown Source)
	at java.base/java.lang.Byte.parseByte(Unknown Source)
	at com.clickhouse.client.data.ClickHouseByteValue.update(ClickHouseByteValue.java:233)
	at com.clickhouse.client.data.ClickHouseByteValue.update(ClickHouseByteValue.java:14)
	at com.clickhouse.client.ClickHouseValue.update(ClickHouseValue.java:1251)
	at com.clickhouse.client.data.ClickHouseByteValue.update(ClickHouseByteValue.java:249)
	at com.clickhouse.client.data.ClickHouseByteValue.update(ClickHouseByteValue.java:14)
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.setObject(InputBasedPreparedStatement.java:420)
	at com.clickhouse.jdbc.ClickHousePreparedStatement.setObject(ClickHousePreparedStatement.java:68)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Version: `0.3.2-patch7`

Expected:
The client is able to accept a string as value for an enum.

**Comment by zhicwu** [comment]
Thanks for reporting the issue. Do you have corresponding enum type in Java? You can pass an num value to set object. I'll enhance the driver by adding a new class (ClickHouseEnum?)  to represent dynamic enum.
