### ISSUE TITLE
Code: 396. DB::Exception: Limit for result exceeded, max bytes: 690.73 MiB, current bytes: 697.25 MiB. (TOO_MANY_ROWS_OR_BYTES) (version 21.11.4.14 (official build))`

### ISSUE THREAD

**Issue by kiwimg** [ClickHouse/clickhouse-jdbc#903]
clickhouse-jdbc version :0.3.1-patch
select id, flow_code,merger_mode from dc_clientorg_all WHERE seller_code GLOBAL IN ( 'W23431111123000' ) and partition_time = toDate('2022-02-01')  and is_invalid IN ('0','2'),
query result count only  110; 

`	... 35 more
Caused by: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: 192.168.2.191, port: 8123; Code: 396. DB::Exception: Limit for result exceeded, max bytes: 690.73 MiB, current bytes: 697.25 MiB. (TOO_MANY_ROWS_OR_BYTES) (version 21.11.4.14 (official build))
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:92)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:56)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:29)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.checkForErrorAndThrow(ClickHouseStatementImpl.java:1099)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:778)
	at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQueryStatement(ClickHouseStatementImpl.java:272)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.execute(ClickHousePreparedStatementImpl.java:138)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3461)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_execute(FilterEventAdapter.java:440)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_execute(FilterChainImpl.java:3459)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.execute(PreparedStatementProxyImpl.java:167)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.execute(DruidPooledPreparedStatement.java:497)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.queryCursor(PreparedStatementHandler.java:71)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.queryCursor(RoutingStatementHandler.java:84)
	at com.baomidou.mybatisplus.core.executor.MybatisSimpleExecutor.doQueryCursor(MybatisSimpleExecutor.java:81)
	at org.apache.ibatis.executor.BaseExecutor.queryCursor(BaseExecutor.java:178)
	at com.baomidou.mybatisplus.core.executor.MybatisCachingExecutor.queryCursor(MybatisCachingExecutor.java:98)
	at jdk.internal.reflect.GeneratedMethodAccessor223.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy184.queryCursor(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectCursor(DefaultSqlSession.java:123)
	... 38 more
Caused by: java.lang.Throwable: Code: 396. DB::Exception: Limit for result exceeded, max bytes: 690.73 MiB, current bytes: 697.25 MiB. (TOO_MANY_ROWS_OR_BYTES) (version 21.11.4.14 (official build))`

**Comment by kiwimg** [comment]
@

**Comment by zhicwu** [comment]
Hi @kiwimg, what's your expectation? It's server side error so I guess it's not related to JDBC driver?

**Comment by kiwimg** [comment]
> Hi @kiwimg, what's your expectation? It's server side error so I guess it's not related to JDBC driver?

I don't know how to solve it，I modify the server-side configuration， <max_result_bytes>724288000</max_result_bytes>，But it can't solve the problem. It was normal before，I hope to get your help

**Comment by kiwimg** [comment]
> > Hi @kiwimg, what's your expectation? It's server side error so I guess it's not related to JDBC driver?
> 
> I don't know how to solve it，I modify the server-side configuration， <max_result_bytes>724288000</max_result_bytes>，But it can't solve the problem. It was normal before，I hope to get your help

I use Java mybatis MyBatisCursorItemReader，
`    <select id="invokeSql" fetchSize="-2147483648" resultSetType="FORWARD_ONLY" resultType="java.util.HashMap">
        ${sqlString}
    </select>
`

**Comment by zhicwu** [comment]
I'm not sure if I can help with limited inputs. My suggestion would be:
* check if the 110 rows actually took more than 690.73 MBs
* see if you can reproduce the issue on newer version of ClickHouse
* if you suspect the issue is somehow related to legacy JDBC driver, check http request sent to server and see if you can reproduce the issue using curl

A quick search shows there's an open issue may or may not related to your problem - ClickHouse/ClickHouse#29895

**Comment by kiwimg** [comment]
> I'm not sure if I can help with limited inputs. My suggestion would be:
> 
> * check if the 110 rows actually took more than 690.73 MBs
> * see if you can reproduce the issue on newer version of ClickHouse
> * if you suspect the issue is somehow related to legacy JDBC driver, check http request sent to server and see if you can reproduce the issue using curl
> 
> A quick search shows there's an open issue may or may not related to your problem - [ClickHouse/ClickHouse#29895](https://github.com/ClickHouse/ClickHouse/issues/29895)

Thank you very much

**Comment by kiwimg** [comment]
这个问题 我向您请教一下，为什么我查询的数据量不大，但是为啥 报错 TOO_MANY_ROWS_OR_BYTES ，配置文件我也调整大了 但是过了几天 有出现报错， 我有调整这个参数配置 越来越大 达到3G

**Comment by kiwimg** [comment]
数据才3万多条

**Comment by zhicwu** [comment]
30k rows is not a lot, if there's no large columns. Have you tried above suggestions? If you don't have a clue, is the same issue can be reproduced on a newer version of ClickHouse? Also you may try https://kb.altinity.com/altinity-kb-queries-and-syntax/explain-query/.

**Comment by kiwimg** [comment]
![image](https://user-images.githubusercontent.com/13777509/168235370-e9f19321-0ed3-4bb4-8d0b-3ff5b51cea8f.png)

**Comment by kiwimg** [comment]
"SelectWithUnionQuery (children 2)"
  SelectQuery (children 3)
   ExpressionList (children 194)
    。。。。
    。。。。
   TablesInSelectQuery (children 1)
    TablesInSelectQueryElement (children 1)
     TableExpression (children 1)
      TableIdentifier dc_salesflow_all
   Function and (children 1)
    ExpressionList (children 3)
     Function equals (children 1)
      ExpressionList (children 2)
       Identifier partition_time
       Function toDate (children 1)
        ExpressionList (children 1)
         Literal '2022-04-01'
     Function equals (children 1)
      ExpressionList (children 2)
       Identifier clean_sign
       Literal '0'
     Function in (children 1)
      ExpressionList (children 2)
       Identifier is_invalid
"       Literal Tuple_('0', '2')"
 Identifier TabSeparatedWithNamesAndTypes

**Comment by kiwimg** [comment]
同样得sql 结构 同样得sql字段，只是where 后面得条件不同，但数据量10万多，也没有报错。这个sql只有3万多，就报错了 太怪异了

**Comment by zhicwu** [comment]
Sorry @kiwimg that I cannot help you for this one. Perhaps you can create a ticket in server repo with details so that you have better chance to get support?
