### ISSUE TITLE
Compile failed by testInsertDefaultValue failed

### ISSUE THREAD

**Issue by ruanwenjun** [ClickHouse/clickhouse-jdbc#906]
When I follow with the [documentation](https://github.com/ClickHouse/clickhouse-jdbc#build-with-maven) and execute `mvn clean verify`  to compile the project.
I get a error
```java
2022-04-25 20:06:24:309 +0800 [main] DEBUG ClickHouseConnectionImpl - Target node: ClickHouseNode(addr=http:localhost:54851, db=test_statement)@1698261139
[ERROR] Tests run: 280, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 26.137 s <<< FAILURE! - in TestSuite
[ERROR] ru.yandex.clickhouse.BalancedClickhouseDataSourceTest.testIPv6  Time elapsed: 0.009 s  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
        at ru.yandex.clickhouse.BalancedClickhouseDataSourceTest.testIPv6(BalancedClickhouseDataSourceTest.java:328)

[ERROR] com.clickhouse.jdbc.ClickHousePreparedStatementTest.testInsertDefaultValue[DateTime64(3, 'UTC'), '1969-12-31 23:59:59.123', 1969-12-31 23:59:59.123](5)  Time elapsed: 0.051 s  <<< FAILURE!
java.lang.AssertionError: expected [1969-12-31 23:59:59.123] but found [1970-01-01 00:00:00.877]
        at com.clickhouse.jdbc.ClickHousePreparedStatementTest.testInsertDefaultValue(ClickHousePreparedStatementTest.java:1041)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   ClickHousePreparedStatementTest.testInsertDefaultValue:1041 expected [1969-12-31 23:59:59.123] but found [1970-01-01 00:00:00.877]
[ERROR]   BalancedClickhouseDataSourceTest.testIPv6:328 expected [true] but found [false]
[INFO] 
[ERROR] Tests run: 280, Failures: 2, Errors: 0, Skipped: 0

```
My jdk version is 1.8.

It seems we insert the time is before 1970.

BTW, how to import the latest master branch into IDEA, I find we have the grpc code in repo, and when I execute the test case, it will throw below exception.
```java
java.util.ServiceConfigurationError: com.clickhouse.client.ClickHouseClient: com.clickhouse.client.grpc.ClickHouseGrpcClient Unable to get public no-arg constructor

	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:672)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1232)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at com.clickhouse.jdbc.ClickHouseDriver.<clinit>(ClickHouseDriver.java:68)
	at com.clickhouse.jdbc.ClickHouseDataSource.<init>(ClickHouseDataSource.java:35)
	at com.clickhouse.jdbc.JdbcIntegrationTest.newDataSource(JdbcIntegrationTest.java:102)
	at com.clickhouse.jdbc.JdbcIntegrationTest.newDataSource(JdbcIntegrationTest.java:94)
	at com.clickhouse.jdbc.JdbcIntegrationTest.newConnection(JdbcIntegrationTest.java:110)
	at com.clickhouse.jdbc.ClickHousePreparedStatementTest.testInsertDefaultValue(ClickHousePreparedStatementTest.java:1017)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:808)
	at org.testng.TestRunner.run(TestRunner.java:603)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.runSuites(TestNG.java:1092)
	at org.testng.TestNG.run(TestNG.java:1060)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.NoClassDefFoundError: io/grpc/Channel
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3137)
	at java.base/java.lang.Class.getConstructor0(Class.java:3342)
	at java.base/java.lang.Class.getConstructor(Class.java:2151)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:659)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:656)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:667)
	... 37 more
Caused by: java.lang.ClassNotFoundException: io.grpc.Channel
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 45 more
```

**Comment by zhicwu** [comment]
Hi @ruanwenjun, which version of ClickHouse you were using for running integration test(depending on `-DclickhouseVersion`, `-DclickhouseServer` or `~/.clickhouse/test.properties`)? DateTime64 does not work properly in old version, but I should enhance the case to avoid that. IPv6 is something different, you have to enable ipv6 to run the test.

As to IDE, I myself use VSCode which works just fine. I think you may need some plugins on IntelliJ for gRPC support?

**Comment by ruanwenjun** [comment]
> 

Thanks for your reply, the clickhosue image for IT is `clickhouse/clickhouse-server:latest`(22.4.2.1), and after I add below dependencies into `clickhouse-jdbc`'s pom, the test case can run successfully.
```pom
<dependency>
    <groupId>com.clickhouse</groupId>
    <artifactId>io.grpc</artifactId>
    <version>1.1.2</version>
</dependency>
<dependency>
    <groupId>com.clickhouse</groupId>
    <artifactId>org.roaringbitmap</artifactId>
    <version>1.1.2</version>
</dependency>
``` 
But there still an assert error.
```
java.lang.AssertionError: 
Expected :1969-12-31 23:59:59.123
Actual   :1970-01-01 00:00:00.877
```

**Comment by zhicwu** [comment]
> after I add below dependencies into `clickhouse-jdbc`'s pom, the test case can run successfully.
> 
> ```
> <dependency>
>     <groupId>com.clickhouse</groupId>
>     <artifactId>io.grpc</artifactId>
>     <version>1.1.2</version>
> </dependency>
> <dependency>
>     <groupId>com.clickhouse</groupId>
>     <artifactId>org.roaringbitmap</artifactId>
>     <version>1.1.2</version>
> </dependency>
> ```

Not sure if this is related to specific IDE or not. Below dependency should have covered above two already. Perhaps you need to run `mvn -Drelease clean install` in `clickhouse-grpc-client` module first?
```xml
<dependency>
    <groupId>${project.parent.groupId}</groupId>
    <artifactId>clickhouse-grpc-client</artifactId>
    <classifier>netty</classifier>
    <version>${revision}</version>
    <exclusions>
        <exclusion>
            <groupId>*</groupId>
            <artifactId>*</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

> But there still an assert error.

It's an issue with ClickHouse 22.4, but I added a workaround to fix IT failure.
