### ISSUE TITLE
How to connect to play.clickhouse.com?

### ISSUE THREAD

**Issue by tisonkun** [ClickHouse/clickhouse-jdbc#953]
I'd like to write my own query as described in https://ghe.clickhouse.tech/#let-s-play-with-the-data.

ClickHouse JDBC driver version: `implementation 'com.clickhouse:clickhouse-jdbc:0.3.2-patch9'`

Related code:

```java
    @Bean
    public DataSource dataSource() {
        final var dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("com.clickhouse.jdbc.ClickHouseDriver");
        dataSource.setUrl("jdbc:ch://play.clickhouse.com:443");
        dataSource.setUsername("explorer");
        return dataSource;
    }

    @PostConstruct
    public void construct() {
        System.out.println("construct");
        final var result = this.jdbcTemplate.queryForRowSet("SELECT 1 FROM github_events");
        System.out.println(result);
    }
```

Get error:

```
Caused by: java.sql.SQLException: Unexpected end of file from server, server ClickHouseNode(addr=http:play.clickhouse.com/<unresolved>:443, db=default)@218028537
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:55) ~[clickhouse-jdbc-0.3.2-patch9.jar:clickhouse-jdbc 0.3.2-patch9 (revision: afa6cdd)]
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:70) ~[clickhouse-jdbc-0.3.2-patch9.jar:clickhouse-jdbc 0.3.2-patch9 (revision: afa6cdd)]
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getServerInfo(ClickHouseConnectionImpl.java:84) ~[clickhouse-jdbc-0.3.2-patch9.jar:clickhouse-jdbc 0.3.2-patch9 (revision: afa6cdd)]
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:245) ~[clickhouse-jdbc-0.3.2-patch9.jar:clickhouse-jdbc 0.3.2-patch9 (revision: afa6cdd)]
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:213) ~[clickhouse-jdbc-0.3.2-patch9.jar:clickhouse-jdbc 0.3.2-patch9 (revision: afa6cdd)]
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:145) ~[clickhouse-jdbc-0.3.2-patch9.jar:clickhouse-jdbc 0.3.2-patch9 (revision: afa6cdd)]
	at com.clickhouse.jdbc.ClickHouseDriver.connect(ClickHouseDriver.java:41) ~[clickhouse-jdbc-0.3.2-patch9.jar:clickhouse-jdbc 0.3.2-patch9 (revision: afa6cdd)]
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681) ~[java.sql:na]
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:190) ~[java.sql:na]
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:155) ~[spring-jdbc-6.0.0-M4.jar:6.0.0-M4]
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:146) ~[spring-jdbc-6.0.0-M4.jar:6.0.0-M4]
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:205) ~[spring-jdbc-6.0.0-M4.jar:6.0.0-M4]
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:169) ~[spring-jdbc-6.0.0-M4.jar:6.0.0-M4]
	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:159) ~[spring-jdbc-6.0.0-M4.jar:6.0.0-M4]
	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:117) ~[spring-jdbc-6.0.0-M4.jar:6.0.0-M4]
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:80) ~[spring-jdbc-6.0.0-M4.jar:6.0.0-M4]
	... 34 common frames omitted
Caused by: java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:903) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:726) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:900) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:726) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1688) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[na:na]
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) ~[na:na]
	at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:137) ~[clickhouse-http-client-0.3.2-patch9-shaded.jar:na]
	at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:251) ~[clickhouse-http-client-0.3.2-patch9-shaded.jar:na]
	at com.clickhouse.client.http.ClickHouseHttpClient.postRequest(ClickHouseHttpClient.java:88) ~[clickhouse-http-client-0.3.2-patch9-shaded.jar:na]
	at com.clickhouse.client.http.ClickHouseHttpClient.execute(ClickHouseHttpClient.java:114) ~[clickhouse-http-client-0.3.2-patch9-shaded.jar:na]
	at com.clickhouse.client.ClickHouseRequest.execute(ClickHouseRequest.java:1466) ~[clickhouse-grpc-client-0.3.2-patch9-netty.jar:na]
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getServerInfo(ClickHouseConnectionImpl.java:77) ~[clickhouse-jdbc-0.3.2-patch9.jar:clickhouse-jdbc 0.3.2-patch9 (revision: afa6cdd)]
	... 47 common frames omitted
```

I guess it should be something wrong with the url but I cannot get an idea :(

**Comment by zhicwu** [comment]
Hi @tisonkun, you can change the URL to `jdbc:ch://play.clickhouse.com:443?ssl=true`.

**Comment by tisonkun** [comment]
@zhicwu Thank you! It works.
