### ISSUE TITLE
random ClickHouseUnknownException, code: 1002 

### ISSUE THREAD

**Issue by smartlee** [ClickHouse/clickhouse-jdbc#994]
the stack:

`ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: x.x.x.x, port: xx; null
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:92) ~[FlinksqlExecutor-pre1.0.0.jar:?]
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:42)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:25) 
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:1071) 
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:1026) 
	at ru.yandex.clickhouse.ClickHouseStatementImpl.sendStream(ClickHouseStatementImpl.java:1019) 
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:381) 
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.executeBatch(ClickHousePreparedStatementImpl.java:364) org.apache.flink.connector.clickhouse.internal.executor.ClickHouseExecutor.attemptExecuteBatch(ClickHouseExecutor.java:61) org.apache.flink.connector.clickhouse.internal.executor.ClickHouseBatchExecutor.executeBatch(ClickHouseBatchExecutor.java:162)
	at org.apache.flink.connector.clickhouse.internal.AbstractClickHouseOutputFormat.checkBeforeFlush(AbstractClickHouseOutputFormat.java:93) `

and clickhouse-server version is `21.8.10.19` 
keep_alive_timeout is 300
clickhouse-jdbc version is `0.3.2`

**Comment by zhicwu** [comment]
Hi @smartlee, is it a modified version of JDBC driver? I didn't find any clue based on above stack trace.

https://github.com/ClickHouse/clickhouse-jdbc/blob/v0.3.2/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java#L1071

**Comment by smartlee** [comment]
@zhicwu thx for reply , I mistake the clickhouse-jdbc version, it's 0.3.1 
https://github.com/ClickHouse/clickhouse-jdbc/blob/v0.3.1/clickhouse-jdbc/src/main/java/ru/yandex/clickhouse/ClickHouseStatementImpl.java#L1071

should i try 0.3.2? the ClickHouseUnknownException return value `null` is confused

**Comment by zhicwu** [comment]
> should i try 0.3.2? 

Yes please. You can bump driver to 0.3.2-patch10 or so to see if the unknown exception is gone. Also I'd suggest you to change driver class to `com.clickhouse.jdbc.ClickHouseDriver`, because you're using a deprecated driver.
